package com.asiainfo.biapp.mcd.tactics.vo;

import javax.persistence.Column;

/**
 * DimCampDrvType generated by MyEclipse - Hibernate Tools
 */

public class DimCampDrvType implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3222740974098166888L;

	// Fields    
	@Column(name="CAMP_DRV_ID")
	private Short campDrvId;

	@Column(name="PARENT_ID")
	private Short parentId;

	@Column(name="FLOW_ID")
	private String flowId;

	@Column(name="plan_exec_id")
	private String planExecId;

	@Column(name="CAMP_DRV_NAME")
	private String campDrvName;

	@Column(name="CAMP_DRV_DESC")
	private String campDrvDesc;
	
	@Column(name="access_control_flag")
	private Short accessControlFlag;
	
	@Column(name="camp_drv_class")
	private Short campDrvClass;
	
	
	@Column(name="dcp_page_id")
	private Integer dcpPageId;
	/** 该驱动类型是否禁用，0：正常不禁用； 1：禁用 */
	@Column(name="DRV_DISABLED")
	private Short drvDesabled;
	
	@Column(name="CAMP_DRV_AUTO_FLAG")
	private Short campDrvAutoFlag;


	// Constructors

	/** default constructor */
	public DimCampDrvType() {
	}

	/** minimal constructor */
	public DimCampDrvType(Short campDrvId) {
		this.campDrvId = campDrvId;
	}

	/** full constructor */
	public DimCampDrvType(Short campDrvId, String campDrvName, String campDrvDesc) {
		this.campDrvId = campDrvId;
		this.campDrvName = campDrvName;
		this.campDrvDesc = campDrvDesc;
	}

	// Property accessors

	public Short getCampDrvId() {
		return this.campDrvId;
	}
	
	public void setCampDrvId(Short campDrvId) {
		this.campDrvId = campDrvId;
	}

	public String getCampDrvName() {
		return this.campDrvName;
	}
	
	public void setCampDrvName(String campDrvName) {
		this.campDrvName = campDrvName;
	}

	public String getCampDrvDesc() {
		return this.campDrvDesc;
	}
	
	public void setCampDrvDesc(String campDrvDesc) {
		this.campDrvDesc = campDrvDesc;
	}

	public Short getParentId() {
		return parentId;
	}
	
	public void setParentId(Short parentId) {
		this.parentId = parentId;
	}

	/**
	 * @return flowId
	 */
	public String getFlowId() {
		return flowId;
	}

	
	public void setFlowId(String flowId) {
		this.flowId = flowId;
	}

	/**
	 * @return planExecId
	 */
	public String getPlanExecId() {
		return planExecId;
	}

	public Integer getDcpPageId() {
		return dcpPageId;
	}
	
	public void setDcpPageId(Integer dcpPageId) {
		this.dcpPageId = dcpPageId;
	}

	/**
	 * @param planExecId 要设置的 planExecId
	 */
	public void setPlanExecId(String planExecId) {
		this.planExecId = planExecId;
	}

	public Short getAccessControlFlag() {
		return accessControlFlag;
	}
	
	public void setAccessControlFlag(Short accessControlFlag) {
		this.accessControlFlag = accessControlFlag;
	}
	
	public Short getCampDrvClass() {
		return campDrvClass;
	}
	
	public void setCampDrvClass(Short campDrvClass) {
		this.campDrvClass = campDrvClass;
	}

	public Short getDrvDesabled() {
		return drvDesabled;
	}
	
	public void setDrvDesabled(Short drvDesabled) {
		this.drvDesabled = drvDesabled;
	}

	public Short getCampDrvAutoFlag() {
		return campDrvAutoFlag;
	}
	
	public void setCampDrvAutoFlag(Short campDrvAutoFlag) {
		this.campDrvAutoFlag = campDrvAutoFlag;
	}
	
	
}
