package com.asiainfo.biapp.mcd.tactics.vo;

import javax.persistence.Column;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * MtlChannelDef generated by MyEclipse - Hibernate Tools
 */
@Table(name="mcd_camp_channel_list")
public class McdCampChannelList implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	@Column(name="CAMPSEG_ID")
	private String  campId;
	@Column(name="CHANNEL_ID")
	private String channelId;
	@Column(name="CONTACT_TYPE")
	private Integer contactType;
	
	@Transient
	private String channelExtendInfo;
	@Transient
	private Short fmtMessFlag;
	@Transient
	private String testProductNo;
	@Transient
	private String channelName;
	@Transient
	private String feedbackinfo;
	@Transient
	private String oriChannelContent;
	@javax.persistence.Column(name="IF_HAVE_VAR")
	private Short ifHaveVar; //是否具有替换符,0:无;1:有
	@javax.persistence.Column(name="EXEC_CONTENT")
	private String execContent;
	@Transient
	private String sxRecommendDesc;//陕西推荐对象描述
	@Transient
	private String onlineServiceUrl;//陕西网上营业厅url
	@Transient
	private String exeContentType;//营销用语类型
	@Transient
	private String campsegInstruct;//营销指令
	@javax.persistence.Column(name="TARGER_USER_NUMS")
	private int targetUserNums;  //目标客户群
	@Transient
	private Integer sendTimeLimit;//短信派发时限字段，用于限定渠道短信派发的时间（单位：天）:
	@javax.persistence.Column(name="UPDATE_CYCLE")
	private int updateCycle;
	@javax.persistence.Column(name="PARAM_DAYS")
	private int paramDays;  //频次控制间隔天数
	@javax.persistence.Column(name="PARAM_NUM")
	private int paramNum;   //频次控制发送次数
	@javax.persistence.Column(name="AWARD_MOUNT")
	private Double awardMount; //奖励金额
	@javax.persistence.Column(name="EDIT_URL")
	private String editUrl; //采编路径
	@javax.persistence.Column(name="HANDLE_URL")
	private String handleUrl; // 办理路径
	@javax.persistence.Column(name="SEND_SMS")
	private String sendSms ; // 短信用语
	@javax.persistence.Column(name="CHANNEL_ADIV_ID")
	private String channelAdivId;  //运营位id
	@Transient
	private int cepTriggerFlag;  //判断是否是实施触发
	@Transient
	private boolean isChoose;  //该渠道在修改之前是否进行过操作  比如增删改查
	@Transient
	private String messageType;   //boss运营位  引用语类型
	@javax.persistence.Column(name="EXEC_TITLE")
	private String execTitle; // 微信标题
	@javax.persistence.Column(name="FILE_NAME")
	private String fileName;  //微信本地文件名称
	@javax.persistence.Column(name="EVENT_ACTIVE_TEMPLET_ID")
	private String eventActiveTempletId;
	@javax.persistence.Column(name="EVENT_INSTANCE_DESC")
	private String eventInstanceDesc;
	@javax.persistence.Column(name="EVENT_PARAM_JSON")
	private String eventParamJson;
	@javax.persistence.Column(name="FUNCTION_ID")
	private String functionId;
	@Transient
	private String functionName;

	public String getCampsegId() {
		return campId;
	}

	public void setCampsegId(String campsegId) {
		this.campId = campsegId;
	}

	public String getFunctionName() {
		return functionName;
	}

	public void setFunctionName(String functionName) {
		this.functionName = functionName;
	}

	public String getFunctionId() {
		return functionId;
	}

	public void setFunctionId(String functionId) {
		this.functionId = functionId;
	}

	public String getEventActiveTempletId() {
		return eventActiveTempletId;
	}

	public void setEventActiveTempletId(String eventActiveTempletId) {
		this.eventActiveTempletId = eventActiveTempletId;
	}

	public String getEventInstanceDesc() {
		return eventInstanceDesc;
	}

	public void setEventInstanceDesc(String eventInstanceDesc) {
		this.eventInstanceDesc = eventInstanceDesc;
	}

	public String getEventParamJson() {
		return eventParamJson;
	}

	public void setEventParamJson(String eventParamJson) {
		this.eventParamJson = eventParamJson;
	}

	public String getChannelAdivId() {
		return channelAdivId;
	}

	public void setChannelAdivId(String channelAdivId) {
		this.channelAdivId = channelAdivId;
	}

	public int getTargetUserNums() {
		return targetUserNums;
	}

	public void setTargetUserNums(int targetUserNums) {
		this.targetUserNums = targetUserNums;
	}

	public int getUpdateCycle() {
		return updateCycle;
	}

	public void setUpdateCycle(int updateCycle) {
		this.updateCycle = updateCycle;
	}

	public Integer getSendTimeLimit() {
		return sendTimeLimit;
	}

	public void setSendTimeLimit(Integer sendTimeLimit) {
		this.sendTimeLimit = sendTimeLimit;
	}

	public String getExeContentType() {
		return exeContentType;
	}

	public void setExeContentType(String exeContentType) {
		this.exeContentType = exeContentType;
	}

	public String getCampsegInstruct() {
		return campsegInstruct;
	}

	public void setCampsegInstruct(String campsegInstruct) {
		this.campsegInstruct = campsegInstruct;
	}

	public boolean getIsChoose() {
		return isChoose;
	}

	public void setChoose(boolean isChoose) {
		this.isChoose = isChoose;
	}

	/**
	 * 扩展字段，用于派单也面显礄1�7
	 * @return
	 */
	public String getChannelName() {
		return channelName;
	}

	public void setChannelName(String channelName) {
		this.channelName = channelName;
	}

	/** default constructor */
	public McdCampChannelList() {
	}

	public String getChannelExtendInfo() {
		return channelExtendInfo;
	}

	public void setChannelExtendInfo(String channelExtendInfo) {
		this.channelExtendInfo = channelExtendInfo;
	}

	public Short getFmtMessFlag() {
		return fmtMessFlag;
	}

	public void setFmtMessFlag(Short fmtMessFlag) {
		this.fmtMessFlag = fmtMessFlag;
	}

	public String getTestProductNo() {
		return testProductNo;
	}

	public void setTestProductNo(String testProductNo) {
		this.testProductNo = testProductNo;
	}

	public String getChannelId() {
		return channelId;
	}

	public void setChannelId(String channelId) {
		this.channelId = channelId;
	}

	public Integer getContactType() {
		return contactType;
	}

	public void setContactType(Integer contactType) {
		this.contactType = contactType;
	}

	public String getFeedbackinfo() {
		return feedbackinfo;
	}

	public void setFeedbackinfo(String feedbackinfo) {
		this.feedbackinfo = feedbackinfo;
	}

	public String getOriChannelContent() {
		return oriChannelContent;
	}

	public void setOriChannelContent(String oriChannelContent) {
		this.oriChannelContent = oriChannelContent;
	}

	public Short getIfHaveVar() {
		return ifHaveVar;
	}

	public void setIfHaveVar(Short ifHaveVar) {
		this.ifHaveVar = ifHaveVar;
	}

	public String getExecContent() {
		return execContent;
	}

	public void setExecContent(String execContent) {
		this.execContent = execContent;
	}

	public String getSxRecommendDesc() {
		return sxRecommendDesc;
	}

	public void setSxRecommendDesc(String sxRecommendDesc) {
		this.sxRecommendDesc = sxRecommendDesc;
	}

	public String getOnlineServiceUrl() {
		return onlineServiceUrl;
	}

	public void setOnlineServiceUrl(String onlineServiceUrl) {
		this.onlineServiceUrl = onlineServiceUrl;
	}

	public int getCepTriggerFlag() {
		return cepTriggerFlag;
	}

	public void setCepTriggerFlag(int cepTriggerFlag) {
		this.cepTriggerFlag = cepTriggerFlag;
	}

	public int getParamDays() {
		return paramDays;
	}

	public void setParamDays(int paramDays) {
		this.paramDays = paramDays;
	}

	public int getParamNum() {
		return paramNum;
	}

	public void setParamNum(int paramNum) {
		this.paramNum = paramNum;
	}

	public Double getAwardMount() {
		return awardMount;
	}

	public void setAwardMount(Double awardMount) {
		this.awardMount = awardMount;
	}

	public String getEditUrl() {
		return editUrl;
	}

	public void setEditUrl(String editUrl) {
		this.editUrl = editUrl;
	}

	public String getHandleUrl() {
		return handleUrl;
	}

	public void setHandleUrl(String handleUrl) {
		this.handleUrl = handleUrl;
	}

	public String getSendSms() {
		return sendSms;
	}

	public void setSendSms(String sendSms) {
		this.sendSms = sendSms;
	}

	public String getExecTitle() {
		return execTitle;
	}

	public void setExecTitle(String execTitle) {
		this.execTitle = execTitle;
	}

	public String getFileName() {
		return fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	public String getMessageType() {
		return messageType;
	}

	public void setMessageType(String messageType) {
		this.messageType = messageType;
	}


	
}
