package com.asiainfo.biapp.mcd.tactics.vo;

import javax.persistence.Column;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * MtlChannelDef generated by MyEclipse - Hibernate Tools
 */
@Table(name="mcd_camp_channel_list")
public class McdCampChannelList implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	@Column(name="CAMPSEG_ID")
	private String  campId;
	@Column(name="CHANNEL_ID")
	private String channelId;
	@Column(name="CONTACT_TYPE")
	private Integer contactType;
	@Column(name="IF_HAVE_VAR")
	private Short isHasVar; //是否具有替换符,0:无;1:有
	@Column(name="EXEC_CONTENT")
	private String execContent;
	@Column(name="TARGER_USER_NUMS")
	private int targetUserNums;  //目标客户群
	@Column(name="UPDATE_CYCLE")
	private int updateCycle;
	@Column(name="PARAM_DAYS")
	private int paramDays;  //频次控制间隔天数
	@Column(name="PARAM_NUM")
	private int paramNum;   //频次控制发送次数
	@Column(name="AWARD_MOUNT")
	private Double awardMount; //奖励金额
	@Column(name="EDIT_URL")
	private String editUrl; //采编路径
	@Column(name="HANDLE_URL")
	private String handleUrl; // 办理路径
	@Column(name="SEND_SMS")
	private String sendSms ; // 短信用语
	@Column(name="CHANNEL_ADIV_ID")
	private String adivId;  //运营位id
	@Column(name="BOSS_SMS_TEMPLATE_ID")
	private String bossTemplateId;//Boss运营位短信模板id
	@Column(name="EXEC_TITLE")
	private String wcTitle; // 微信标题
	@Column(name="FILE_NAME")
	private String wcFileName;  //微信本地文件名称
	@Column(name="EVENT_INSTANCE_DESC")
	private String eventInstanceDesc;
	@Column(name="EVENT_PARAM_JSON")
	private String eventParamJson;
	@Column(name="FUNCTION_ID")
	private String functionId;
	@Transient
	private String messageType;   //boss运营位  引用语类型
	@Transient
	private String channelName;
	@Transient
	private String functionName;

	public String getBossTemplateId() {
		return bossTemplateId;
	}
	public void setBossTemplateId(String bossTemplateId) {
		this.bossTemplateId = bossTemplateId;
	}
	public String getCampId() {
		return campId;
	}
	public void setCampId(String campId) {
		this.campId = campId;
	}
	public String getChannelId() {
		return channelId;
	}
	public void setChannelId(String channelId) {
		this.channelId = channelId;
	}
	public Integer getContactType() {
		return contactType;
	}
	public void setContactType(Integer contactType) {
		this.contactType = contactType;
	}
	
	public String getExecContent() {
		return execContent;
	}
	public void setExecContent(String execContent) {
		this.execContent = execContent;
	}
	public int getTargetUserNums() {
		return targetUserNums;
	}
	public void setTargetUserNums(int targetUserNums) {
		this.targetUserNums = targetUserNums;
	}
	public int getUpdateCycle() {
		return updateCycle;
	}
	public void setUpdateCycle(int updateCycle) {
		this.updateCycle = updateCycle;
	}
	public int getParamDays() {
		return paramDays;
	}
	public void setParamDays(int paramDays) {
		this.paramDays = paramDays;
	}
	public int getParamNum() {
		return paramNum;
	}
	public void setParamNum(int paramNum) {
		this.paramNum = paramNum;
	}
	public Double getAwardMount() {
		return awardMount;
	}
	public void setAwardMount(Double awardMount) {
		this.awardMount = awardMount;
	}
	public String getEditUrl() {
		return editUrl;
	}
	public void setEditUrl(String editUrl) {
		this.editUrl = editUrl;
	}
	public String getHandleUrl() {
		return handleUrl;
	}
	public void setHandleUrl(String handleUrl) {
		this.handleUrl = handleUrl;
	}
	public String getSendSms() {
		return sendSms;
	}
	public void setSendSms(String sendSms) {
		this.sendSms = sendSms;
	}
	public String getAdivId() {
		return adivId;
	}
	public void setAdivId(String channelAdivId) {
		this.adivId = channelAdivId;
	}
	public String getWcTitle() {
		return wcTitle;
	}
	public void setWcTitle(String wcTitle) {
		this.wcTitle = wcTitle;
	}
	public String getWcFileName() {
		return wcFileName;
	}
	public void setWcFileName(String wcFileName) {
		this.wcFileName = wcFileName;
	}
	public String getEventInstanceDesc() {
		return eventInstanceDesc;
	}
	public void setEventInstanceDesc(String eventInstanceDesc) {
		this.eventInstanceDesc = eventInstanceDesc;
	}
	public String getEventParamJson() {
		return eventParamJson;
	}
	public void setEventParamJson(String eventParamJson) {
		this.eventParamJson = eventParamJson;
	}
	public String getFunctionId() {
		return functionId;
	}
	public void setFunctionId(String functionId) {
		this.functionId = functionId;
	}
	public String getMessageType() {
		return messageType;
	}
	public void setMessageType(String messageType) {
		this.messageType = messageType;
	}
	public String getChannelName() {
		return channelName;
	}
	public void setChannelName(String channelName) {
		this.channelName = channelName;
	}
	public String getFunctionName() {
		return functionName;
	}
	public void setFunctionName(String functionName) {
		this.functionName = functionName;
	}
	public Short getIsHasVar() {
		return isHasVar;
	}
	public void setIsHasVar(Short isHasVar) {
		this.isHasVar = isHasVar;
	}	

}
