package com.asiainfo.biapp.mcd.tactics.vo;

import java.util.Date;
/**
 * DimCampPri generated by MyEclipse - Hibernate Tools
 */

public class MtlCallwsUrl implements java.io.Serializable {

	// Fields    

	private String callwsUrlCode;

	private String callwsUrlName;

	private String callwsUrl;
	
	private String callwsUrlDesc;

	private Short callwsUrlType;

	private Short oppositeType;
	
	private Date createDate;

	private String createUserid;
	
	private String oppositeName;
	
	private String callwsUrlClass;

	// Constructors

	/** default constructor */
	public MtlCallwsUrl() {
	}

	/** minimal constructor */
	public MtlCallwsUrl(String callwsUrlCode) {
		this.callwsUrlCode = callwsUrlCode;
	}

	public String getCallwsUrlCode() {
		return callwsUrlCode;
	}

	public void setCallwsUrlCode(String callwsUrlCode) {
		this.callwsUrlCode = callwsUrlCode;
	}

	public String getCallwsUrlName() {
		return callwsUrlName;
	}

	public void setCallwsUrlName(String callwsUrlName) {
		this.callwsUrlName = callwsUrlName;
	}	

	public String getCallwsUrl() {
		return callwsUrl;
	}

	public void setCallwsUrl(String callwsUrl) {
		this.callwsUrl = callwsUrl;
	}  
	
	public String getCallwsUrlDesc() {
		return callwsUrlDesc;
	}

	public void setCallwsUrlDesc(String callwsUrlDesc) {
		this.callwsUrlDesc = callwsUrlDesc;
	}  
	
	public Short getCallwsUrlType() {
		return callwsUrlType;
	}

	public void setCallwsUrlType(Short callwsUrlType) {
		this.callwsUrlType = callwsUrlType;
	}  	
	public Short getOppositeType() {
		return oppositeType;
	}

	public void setOppositeType(Short oppositeType) {
		this.oppositeType = oppositeType;
	}  
	
	public Date getCreateDate() {
		return createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	} 
	
	public String getCreateUserid() {
		return createUserid;
	}

	public void setCreateUserid(String createUserid) {
		this.createUserid = createUserid;
	} 
	public String getOppositeName() {
		return oppositeName;
	}

	public void setOppositeName(String oppositeName) {
		this.oppositeName = oppositeName;
	} 	
	public String getCallwsUrlClass() {
		return callwsUrlClass;
	}

	public void setCallwsUrlClass(String callwsUrlClass) {
		this.callwsUrlClass = callwsUrlClass;
	} 		
	
	
}
