package com.asiainfo.biapp.mcd.tactics.vo;

import java.util.Date;
import java.util.List;
import java.util.Locale;
import java.util.Set;

/**
 * MtlCampSeginfo generated by MyEclipse - Hibernate Tools
 */

public class MtlCampSeginfo {
    //当前页
    private Integer pageNum;
    //查询的是否是自己的 0 ：是     1 ：不是

    private Integer isSelectMy;
    //是否是浙江
    private Boolean isZJ;
    //是否是自己创建的  0 ：是     1 ：不是
    private Integer isMy;
    //业务类型可多选情况
    private String campDrvIds;
    //状态名称
    private String campsegStatName;
    private Short campsegStatId; // 营销活动状态ID
    private String channelId;
    private String channelTypeId;
    private String createUserid; // 活动策划人
    private String keywords;// 关键字
    private String areaId; // 营销活动所属地区
    
    
    public Integer getPageNum() {
        return pageNum;
    }
    public void setPageNum(Integer pageNum) {
        this.pageNum = pageNum;
    }
    public Integer getIsSelectMy() {
        return isSelectMy;
    }
    public void setIsSelectMy(Integer isSelectMy) {
        this.isSelectMy = isSelectMy;
    }
    public Boolean getIsZJ() {
        return isZJ;
    }
    public void setIsZJ(Boolean isZJ) {
        this.isZJ = isZJ;
    }
    public Integer getIsMy() {
        return isMy;
    }
    public void setIsMy(Integer isMy) {
        this.isMy = isMy;
    }
    public String getCampDrvIds() {
        return campDrvIds;
    }
    public void setCampDrvIds(String campDrvIds) {
        this.campDrvIds = campDrvIds;
    }
    public String getCampsegStatName() {
        return campsegStatName;
    }
    public void setCampsegStatName(String campsegStatName) {
        this.campsegStatName = campsegStatName;
    }
    public Short getCampsegStatId() {
        return campsegStatId;
    }
    public void setCampsegStatId(Short campsegStatId) {
        this.campsegStatId = campsegStatId;
    }
    public String getChannelId() {
        return channelId;
    }
    public void setChannelId(String channelId) {
        this.channelId = channelId;
    }
    public String getChannelTypeId() {
        return channelTypeId;
    }
    public void setChannelTypeId(String channelTypeId) {
        this.channelTypeId = channelTypeId;
    }
    public String getCreateUserid() {
        return createUserid;
    }
    public void setCreateUserid(String createUserid) {
        this.createUserid = createUserid;
    }
    public String getKeywords() {
        return keywords;
    }
    public void setKeywords(String keywords) {
        this.keywords = keywords;
    }
    public String getAreaId() {
        return areaId;
    }
    public void setAreaId(String areaId) {
        this.areaId = areaId;
    }
    
    
    
}
