package com.asiainfo.biapp.mcd.custgroup.vo;

/**
 * MtlCampsegProgressId generated by MyEclipse - Hibernate Tools
 */

public class MtlCampsegProgressId implements java.io.Serializable {

	// Fields    

	private String campsegId;

	private Short stepId;

	private String flowId;

	// Constructors

	/** default constructor */
	public MtlCampsegProgressId() {
	}

	public MtlCampsegProgressId(String id1, Short id2, String id3) {
		this.campsegId = id1;
		this.stepId = id2;
		this.flowId = id3;
	}

	// Property accessors

	public String getCampsegId() {
		return this.campsegId;
	}

	public void setCampsegId(String campsegId) {
		this.campsegId = campsegId;
	}

	public Short getStepId() {
		return this.stepId;
	}

	public void setStepId(Short stepId) {
		this.stepId = stepId;
	}

	public String getFlowId() {
		return this.flowId;
	}

	public void setFlowId(String flowId) {
		this.flowId = flowId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MtlCampsegProgressId))
			return false;
		MtlCampsegProgressId castOther = (MtlCampsegProgressId) other;

		return ((this.getCampsegId() == castOther.getCampsegId()) || (this.getCampsegId() != null && castOther.getCampsegId() != null && this.getCampsegId().equals(castOther.getCampsegId())))
				&& ((this.getStepId() == castOther.getStepId()) || (this.getStepId() != null && castOther.getStepId() != null && this.getStepId().equals(castOther.getStepId())))
				&& ((this.getFlowId() == castOther.getFlowId()) || (this.getFlowId() != null && castOther.getFlowId() != null && this.getFlowId().equals(castOther.getFlowId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCampsegId() == null ? 0 : this.getCampsegId().hashCode());
		result = 37 * result + (getStepId() == null ? 0 : this.getStepId().hashCode());
		result = 37 * result + (getFlowId() == null ? 0 : this.getFlowId().hashCode());
		return result;
	}

}
