/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Tue Jun 06 16:00:39 CST 2006 by MyEclipse Hibernate Tool.
 */
package com.asiainfo.biapp.mcd.model;

import java.io.Serializable;

/**
 * A class that represents a row in the DIM_PUB_BRAND table. 
 * You can customize the behavior of this class by editing the class, {@link DimPubBrand()}.
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 */
public abstract class AbstractDimPubBrand extends java.lang.Object implements Serializable {
	/** The cached hash code value for this instance.  Settting to 0 triggers re-calculation. */
	private int hashValue = 0;

	/** The composite primary key value. */
	private java.lang.Short brandId;

	/** The value of the simple brandName property. */
	private java.lang.String brandName;
	
	//caolifeng
	private java.lang.Short parentID;

	public java.lang.Short getParentID() {
		return parentID;
	}

	public void setParentID(java.lang.Short parentID) {
		this.parentID = parentID;
	}

	/**
	 * Simple constructor of AbstractDimPubBrand instances.
	 */
	public AbstractDimPubBrand() {
	}

	/**
	 * Constructor of AbstractDimPubBrand instances given a simple primary key.
	 * @param brandId
	 */
	public AbstractDimPubBrand(java.lang.Short brandId) {
		this.brandId = brandId;
	}

	/**
	 * Return the simple primary key value that identifies this object.
	 * @return java.lang.Short
	 */
	public java.lang.Short getBrandId() {
		return brandId;
	}

	/**
	 * Set the simple primary key value that identifies this object.
	 * @param brandId
	 */
	public void setBrandId(java.lang.Short brandId) {
		this.hashValue = 0;
		this.brandId = brandId;
	}

	/**
	 * Return the value of the BRAND_NAME column.
	 * @return java.lang.String
	 */
	public java.lang.String getBrandName() {
		return this.brandName;
	}

	/**
	 * Set the value of the BRAND_NAME column.
	 * @param brandName
	 */
	public void setBrandName(java.lang.String brandName) {
		this.brandName = brandName;
	}

	/**
	 * Implementation of the equals comparison on the basis of equality of the primary key values.
	 * @param rhs
	 * @return boolean
	 */
	@Override
	public boolean equals(Object rhs) {
		if (rhs == null)
			return false;
		if (!(rhs instanceof DimPubBrand))
			return false;
		DimPubBrand that = (DimPubBrand) rhs;
		if (this.getBrandId() == null || that.getBrandId() == null)
			return false;
		return (this.getBrandId().equals(that.getBrandId()));
	}

	/**
	 * Implementation of the hashCode method conforming to the Bloch pattern with
	 * the exception of array properties (these are very unlikely primary key types).
	 * @return int
	 */
	@Override
	public int hashCode() {
		if (this.hashValue == 0) {
			int result = 17;
			int brandIdValue = this.getBrandId() == null ? 0 : this.getBrandId().hashCode();
			result = result * 37 + brandIdValue;
			this.hashValue = result;
		}
		return this.hashValue;
	}
}
