package com.asiainfo.biapp.mcd.model;

/**
 * DimAvoidBother generated by MyEclipse - Hibernate Tools
 */

public class DimAvoidBother implements java.io.Serializable {

	// Fields    

	private DimAvoidBotherId id;

	private String avoidBotherName;

	private String avoidBotherDesc;

	private Short custSystemType;

	private String productNo;

	private String cityId;

	private Short isSystemDefault;

	// Constructors

	public Short getCustSystemType() {
		return custSystemType;
	}

	public void setCustSystemType(Short custSystemType) {
		this.custSystemType = custSystemType;
	}

	/** default constructor */
	public DimAvoidBother() {
	}

	/** minimal constructor */
	public DimAvoidBother(DimAvoidBotherId id) {
		this.id = id;
	}

	/** full constructor */
	public DimAvoidBother(DimAvoidBotherId id, String avoidBotherName, String avoidBotherDesc) {
		this.id = id;
		this.avoidBotherName = avoidBotherName;
		this.avoidBotherDesc = avoidBotherDesc;
	}

	public Short getIsSystemDefault() {
		return isSystemDefault;
	}

	public void setIsSystemDefault(Short isSystemDefault) {
		this.isSystemDefault = isSystemDefault;
	}

	public DimAvoidBotherId getId() {
		return this.id;
	}

	public void setId(DimAvoidBotherId id) {
		this.id = id;
	}

	public String getAvoidBotherName() {
		return avoidBotherName;
	}

	public void setAvoidBotherName(String avoidBotherName) {
		this.avoidBotherName = avoidBotherName;
	}

	public String getAvoidBotherDesc() {
		return avoidBotherDesc;
	}

	public void setAvoidBotherDesc(String avoidBotherDesc) {
		this.avoidBotherDesc = avoidBotherDesc;
	}

	public String getProductNo() {
		return productNo;
	}

	public void setProductNo(String productNo) {
		this.productNo = productNo;
	}

	public String getCityId() {
		return cityId;
	}

	public void setCityId(String cityId) {
		this.cityId = cityId;
	}
}
