package com.asiainfo.biapp.mcd.model;



/**
 * DimDrvRoleManagerId generated by MyEclipse Persistence Tools
 */

public class DimDrvRoleManagerId implements java.io.Serializable {

	// Fields

	private Short campDrvId;
	private String roleId;

	// Constructors

	/** default constructor */
	public DimDrvRoleManagerId() {
	}

	/** full constructor */
	public DimDrvRoleManagerId(Short campDrvId, String roleId) {
		this.campDrvId = campDrvId;
		this.roleId = roleId;
	}

	// Property accessors

	public Short getCampDrvId() {
		return this.campDrvId;
	}

	public void setCampDrvId(Short campDrvId) {
		this.campDrvId = campDrvId;
	}

	public String getRoleId() {
		return this.roleId;
	}

	public void setRoleId(String roleId) {
		this.roleId = roleId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DimDrvRoleManagerId))
			return false;
		DimDrvRoleManagerId castOther = (DimDrvRoleManagerId) other;

		return ((this.getCampDrvId() == castOther.getCampDrvId()) || (this
				.getCampDrvId() != null
				&& castOther.getCampDrvId() != null && this
				.getCampDrvId()
				.equals(castOther.getCampDrvId())))
				&& ((this.getRoleId() == castOther.getRoleId()) || (this
						.getRoleId() != null
						&& castOther.getRoleId() != null && this
						.getRoleId()
						.equals(castOther.getRoleId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getCampDrvId() == null ? 0 : this
						.getCampDrvId().hashCode());
		result = 37
				* result
				+ (getRoleId() == null ? 0 : this.getRoleId()
						.hashCode());
		return result;
	}

}
