package com.asiainfo.biapp.mcd.model;

import java.util.Date;
import java.util.Set;

/**
 * MtlApproveFlowDef generated by MyEclipse - Hibernate Tools
 */

public class MtlApproveFlowDef implements java.io.Serializable {

	// Fields    

	private String approveFlowId;

	private String createUserid;

	private String cityid;

	private String approveFlowName;

	private String confirmId;

	private Date createTime;

	private Short approveFlowLevelCnt;

	private Set approveFlowLevels;

	private String approveFlowDefStr;

	private short approveFlowAccessToken;
	
	private String firstApproveUser;
	
	private String deptId;

	// Constructors

	/**
	 * @return approveFlowAccessToken
	 */
	public short getApproveFlowAccessToken() {
		return approveFlowAccessToken;
	}

	/**
	 * @param approveFlowAccessToken 要设置的 approveFlowAccessToken
	 */
	public void setApproveFlowAccessToken(short approveFlowAccessToken) {
		this.approveFlowAccessToken = approveFlowAccessToken;
	}

	/** default constructor */
	public MtlApproveFlowDef() {
	}

	/** minimal constructor */
	public MtlApproveFlowDef(String approveFlowId, String createUserid, String approveFlowName) {
		this.approveFlowId = approveFlowId;
		this.createUserid = createUserid;
		this.approveFlowName = approveFlowName;
	}

	/** full constructor */
	public MtlApproveFlowDef(String approveFlowId, String createUserid, String cityid, String approveFlowName) {
		this.approveFlowId = approveFlowId;
		this.createUserid = createUserid;
		this.cityid = cityid;
		this.approveFlowName = approveFlowName;
	}

	// Property accessors

	public String getApproveFlowId() {
		return this.approveFlowId;
	}

	public void setApproveFlowId(String approveFlowId) {
		this.approveFlowId = approveFlowId;
	}

	public String getCreateUserid() {
		return this.createUserid;
	}

	public void setCreateUserid(String createUserid) {
		this.createUserid = createUserid;
	}

	public String getConfirmId() {
		return this.confirmId;
	}

	public void setConfirmId(String confirmId) {
		this.confirmId = confirmId;
	}

	public String getCityid() {
		return this.cityid;
	}

	public void setCityid(String cityid) {
		this.cityid = cityid;
	}

	public String getApproveFlowName() {
		return this.approveFlowName;
	}

	public void setApproveFlowName(String approveFlowName) {
		this.approveFlowName = approveFlowName;
	}

	public Date getCreateTime() {
		return createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Set getApproveFlowLevels() {
		return approveFlowLevels;
	}

	public void setApproveFlowLevels(Set approveFlowLevels) {
		this.approveFlowLevels = approveFlowLevels;
	}

	public String getApproveFlowDefStr() {
		return approveFlowDefStr;
	}

	public void setApproveFlowDefStr(String approveFlowDefStr) {
		this.approveFlowDefStr = approveFlowDefStr;
	}

	public Short getApproveFlowLevelCnt() {
		return approveFlowLevelCnt;
	}

	public void setApproveFlowLevelCnt(Short approveFlowLevelCnt) {
		this.approveFlowLevelCnt = approveFlowLevelCnt;
	}

	public String getFirstApproveUser() {
		return firstApproveUser;
	}

	public void setFirstApproveUser(String firstApproveUser) {
		this.firstApproveUser = firstApproveUser;
	}

	public String getDeptId() {
		return deptId;
	}

	public void setDeptId(String deptId) {
		this.deptId = deptId;
	}
	
	
}
