package com.asiainfo.biapp.mcd.model;

import java.util.Date;
import java.util.Set;

import com.asiainfo.biapp.mcd.util.MpmUtil;

/**
 * MtlCampDataSource generated by MyEclipse - Hibernate Tools
 */

public class MtlCampDataSource implements java.io.Serializable {

	// Fields    

	private String sourceName;

	private String sourceCname;

	private String sourceDesc;

	private String sourceType;

	private Date createTime;

	private String sourceStatus;

	private boolean flag = true;

	private Short cycleType;
	
	public Short getCycleType() {
		return cycleType;
	}

	public void setCycleType(Short cycleType) {
		this.cycleType = cycleType;
	}

	public boolean isFlag() {
		return flag;
	}

	public void setFlag(boolean flag) {
		this.flag = flag;
	}

	private Set columns;

	// Constructors

	/** default constructor */
	public MtlCampDataSource() {
		this.flag = true;
	}

	/** minimal constructor */
	public MtlCampDataSource(String sourceName) {
		this.sourceName = sourceName;
	}

	/** full constructor */
	public MtlCampDataSource(String sourceName, String sourceCname, String sourceDesc, String sourceType, Date createTime, String sourceStatus) {
		this.sourceName = sourceName;
		this.sourceCname = sourceCname;
		this.sourceDesc = sourceDesc;
		this.sourceType = sourceType;
		this.createTime = createTime;
		this.sourceStatus = sourceStatus;
	}

	// Property accessors

	public String getSourceName() {

		return this.sourceName;
	}

	public void setSourceName(String sourceName) {
		this.sourceName = sourceName;
	}

	public String getSourceCname() {
		if (this.flag) {
			return MpmUtil.GBToUnicode(this.sourceCname);
		} else {
			return MpmUtil.unicodeToGB(this.sourceCname);
		}
	}

	public void setSourceCname(String sourceCname) {
		this.sourceCname = sourceCname;
	}

	public String getSourceDesc() {
		return this.sourceDesc;
	}

	public void setSourceDesc(String sourceDesc) {
		this.sourceDesc = sourceDesc;
	}

	public String getSourceType() {
		return this.sourceType;
	}

	public void setSourceType(String sourceType) {
		this.sourceType = sourceType;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public String getSourceStatus() {
		return this.sourceStatus;
	}

	public void setSourceStatus(String sourceStatus) {
		this.sourceStatus = sourceStatus;
	}

	public Set getColumns() {
		return columns;
	}

	public void setColumns(Set columns) {
		this.columns = columns;
	}

}
