package com.asiainfo.biapp.mcd.model;

import java.util.Date;

/**
 * MtlCampsegProgress generated by MyEclipse - Hibernate Tools
 */

public class MtlCampsegProgress implements java.io.Serializable {

	// Fields    

	private MtlCampsegProgressId id;

	private Date performTime;

	private String performUserid;

	private Short performFlag;

	private String proformResult;

	private String campId;

	// Constructors

	/** default constructor */
	public MtlCampsegProgress() {
		id = new MtlCampsegProgressId();
	}

	/** minimal constructor */
	public MtlCampsegProgress(MtlCampsegProgressId id, Date performTime) {
		this.id = id;
		this.performTime = performTime;
	}

	/** full constructor */
	public MtlCampsegProgress(MtlCampsegProgressId id, Date performTime, String performUserid, Short performFlag, String proformResult, String campId) {
		this.id = id;
		this.performTime = performTime;
		this.performUserid = performUserid;
		this.performFlag = performFlag;
		this.proformResult = proformResult;
		this.campId = campId;
	}

	// Property accessors

	public MtlCampsegProgressId getId() {
		return this.id;
	}

	public void setId(MtlCampsegProgressId id) {
		this.id = id;
	}

	public Date getPerformTime() {
		return this.performTime;
	}

	public void setPerformTime(Date performTime) {
		this.performTime = performTime;
	}

	public String getPerformUserid() {
		return this.performUserid;
	}

	public void setPerformUserid(String performUserid) {
		this.performUserid = performUserid;
	}

	public Short getPerformFlag() {
		return this.performFlag;
	}

	public void setPerformFlag(Short performFlag) {
		this.performFlag = performFlag;
	}

	public String getProformResult() {
		return this.proformResult;
	}

	public void setProformResult(String proformResult) {
		this.proformResult = proformResult;
	}

	public String getCampId() {
		return this.campId;
	}

	public void setCampId(String campId) {
		this.campId = campId;
	}

}
