package com.asiainfo.biapp.mcd.model;

import java.util.Date;
import java.util.List;
import java.util.Locale;
import java.util.Set;

import com.asiainfo.biapp.mcd.form.McdTempletForm;

/**
 * MtlCampSeginfo generated by MyEclipse - Hibernate Tools
 */

public class MtlCampSeginfo implements java.io.Serializable {
	// Fields
	private Date approveRemindTime;
	private String campsegId; // 活动编号
	private String campId; // 营销案标识
	private String campsegNo; // 活动序号
	private String campsegName; // 活动名称
	private String campName;
	private Short campsegStatId; // 营销活动状态ID
	private String campsegDesc; // 活动描述
	private Short campPriId; // 活动优先级,见维表:dim_camp_pri
	private Short campDrvId; // 活动类型,见维表:dim_camp_drv_type
	private String promotionTypeId; // 促销业务类别,见维表:mtl_promotion_type
	private String scenesId; // 场景标识
	private Short campsegTypeId; // 活动营销类型
	private Short campsegContactFlag; // 是否进行接触控制
	private String publicizeCombId; // 宣传设计组合编号
	private String subCampDrvId;
	private String flowId;
	private String planExecId;
	private String createType;
	private String timeInterval;
	private Integer isFromVgopFlag;
	private String isDelSnap;
	private String busshallId;

	private String startDate; // 开始时间
	private String endDate; // 结束时间
	private String srcdataDate; // 数据匹配日期
	private Date createTime; // 本活动定义时间
	private String toStartDate;
	private String toEndDate;

	private String approveFlowid; // 默认内部审批流程
	private Short approveResult; // 审批结果
	private Short confirmFlag;// 活动确认状态
	private Short approveReceiveNums; // 审批波次
	private String evaluateComment; // 活动中止原因
	private String createUserid; // 活动策划人
	private String cityId; // 策划人所属地市
	private Integer deptId; // 策划人部门id
	private String executeUser; // (辽宁需求)added by caosj 2009-06-04
	private String approveResultDesc;//审批结果描述

	private Integer targerUserNums; // 目标客户数
	private Integer contrastUserNums; // 对比用户数
	private Integer contactedUserNums; // 联系客户数
	private Integer contactOkuserNums; // 联系成功客户数
	private Integer receivedOkuserNums; // 营销成功客户数
	private Integer campsegMaxUsers; // 最大客户数
	private Integer campsegContrastUsers; // 对比用户群客户数
	private Integer CampsegContactUsernums; // 活动被接触控制的用户数

	private String filePath;

	private Short formatMessFlag; // 格式化信息标记（北京需求）added by caosj 2009-8-10
	private String testProductNo; // 额外测试号码（北京需求） added by caosj 2009-8-10
	private String channelExtendInfo; // 营业厅渠道附加信息（北京需求） added by caosj
										// 2009-8-10

	private String campsegBussiCode;
	private Integer containOutProvince; // 是否包含外省用户
	private Integer supportWifi; // 是否支持Wifi
	private Short isTemplate; // 是否为模板 added by fuyu
	private Integer sendtimeDelay; // 延迟发送时间,单位时
	private String sceneType; // 活动场景类型
	private String timeRange; // 营销时段，可多个，逗号分隔 eg.
								// 00:30-08:00,10:20-16:40,21:20-23:50
	private String avoidTimeRange;
	private Integer contactType; // 活动级接触类型
	private Integer contactCount;
	/** 活动级接触控制次数 */
	private Integer waveContactType; // 规则接触类型
	private Integer waveContactCount;
	/** 规则级接触控制次数 */

	private String campsegPid; // 活动编号父ID
	private Integer campClass; // 活动实际含义1：活动基本信息,2：规则,3：波次
	private String waveConId; // 波次响应条件
	private Integer campWaveDelay; // 波次执行延迟时间
	private String planId; // 资费编码
	private Integer executeStatus; // 执行渠道响应状态,多波次时0：未响应,1：已响应
	private String areaId; // 营销活动所属地区
	private String areaName; // 营销活动所属地区名称
	private String activeTempletId;// 时机规则模板ID
	private String eventActiveTempletId;// 事件规则模板ID
	private String custListTabName;// 客户群清单表名
	private Integer isRelativeExecTime; // 执行时间是否相对时间
	private String absoluteDates; // 绝对时间串，逗号分隔
	private Integer campWaveDelayFrom; // 多波次执行延迟相对时间开始
	private Integer campWaveDelayTo; // 波次执行延迟相对时间结束
	private Integer isWaitFrontOver; // 是否等待前一波次执行完成后执行
	private String channelCampContent; // 营销用语
	private String currentTaskId;// 当前任务编号
	private String rejectCampsegIds;// 剔除活动编号
	private String avoidBotherTypeIds;// 免打扰客户类型ID
	private String systemId; // 挂载外部系统ID
	private String selectTempletId; // 筛选规则模板id
	private String initCustListTab;//策略初始清单表
	
	// 数据库不存在的字段
	private String custgroupId; // 客户群
	private String channelId;
	private String channelTypeId;

	private String interactionRule; // 互动规则
	private String interactionView; // 互动语句

	private Set campsegAttachs; // 附件
	private Set campsegProgress;
	private Set campsegUsersegs;
	private String confirmState;
	private String confirmUserId;
	private boolean isTest;// 是否测试
	private String campDrvName;// 活动类型名称
	private String testNumber; // 测试号码
	private String custGroupAttrId;
	private int custGroupNum;
	private String channelName;
	private String firstApproveUserId;
	private String recommendDesc;
	// 陕西网上营业厅url
	private String onlineServiceUrl;

	private String currentUserId;
	// 营销规则ID，多个逗号分隔
	private String ruleIds;

	// 客户群类型(0:无 ,1:客户群 2:来自其他活动规则的反馈)
	private Integer targetCustType;

	// 是否按渠道类型拆分活动规则
	private int splitCampSegInfo;

	// 派单时是否按客户偏好自动选择渠道
	private Short isSplitCustgroup;
	
	private Integer isFileterDisturb;

	public Integer getIsFileterDisturb() {
		return isFileterDisturb;
	}

	public void setIsFileterDisturb(Integer isFileterDisturb) {
		this.isFileterDisturb = isFileterDisturb;
	}

	// 客户群 来自其他活动规则的反馈 信息
	private McdTargetCustFeedback mcdTargetCustFeedback;

	/**
	 * 活动规则的渠道执行为综合网关时的内容站点、网站分类ID的关联(json字符串)
	 */
	private String siteCategoryIdClassId;

	private Integer is_containFee;// 是否包含费用
	
	//当前页
	private Integer pageNum;
	//查询的是否是自己的 0 ：是     1 ：不是

	private Integer isSelectMy;
	//是否是浙江
	private Boolean isZJ;
	//是否是自己创建的  0 ：是     1 ：不是
	private Integer isMy;
	//业务类型可多选情况
	private String campDrvIds;
	//状态名称
	private String campsegStatName;
	 
	private String custGroupName;
	private String custgroupType;
	private Integer custgroupNumber;
	private String custBaseMonth;
	private String custBaseDay;
	
	private String basicEventTemplateId;
	private String bussinessLableTemplateId;
	
	private McdTempletForm bussinessLableTemplate;
	private McdTempletForm basicEventTemplate;
	private Locale requestLocal;
	private String createUserName;
	
	//产品订购ID
	private String orderPlanIds;
	//剔除产品ID
	private String excludePlanIds;
	
	private String updatecycle;  //客户群更新周期
	private List<MtlChannelDef> mtlChannelDefList;   //渠道执行
	
	private boolean isFatherNode;  //是否为策略基础信息；true:是基本信息；false:子规则
	
	private String isApprove;
	
	private String planName;
	
	private MtlChannelDefCall mtlChannelDefCall;//渠道对应表_外呼

	public Date getApproveRemindTime() {
		return approveRemindTime;
	}

	public void setApproveRemindTime(Date approveRemindTime) {
		this.approveRemindTime = approveRemindTime;
	}

	public String getPlanName() {
		return planName;
	}

	public void setPlanName(String planName) {
		this.planName = planName;
	}

	public String getIsApprove() {
		return isApprove;
	}

	public void setIsApprove(String isApprove) {
		this.isApprove = isApprove;
	}

	public Locale getRequestLocal() {
		return requestLocal;
	}

	public void setRequestLocal(Locale requestLocal) {
		this.requestLocal = requestLocal;
	}

	public McdTempletForm getBussinessLableTemplate() {
		return bussinessLableTemplate;
	}

	public void setBussinessLableTemplate(McdTempletForm bussinessLableTemplate) {
		this.bussinessLableTemplate = bussinessLableTemplate;
	}

	public McdTempletForm getBasicEventTemplate() {
		return basicEventTemplate;
	}

	public void setBasicEventTemplate(McdTempletForm basicEventTemplate) {
		this.basicEventTemplate = basicEventTemplate;
	}

	public boolean isFatherNode() {
		return isFatherNode;
	}

	public void setFatherNode(boolean isFatherNode) {
		this.isFatherNode = isFatherNode;
	}

	public String getUpdatecycle() {
		return updatecycle;
	}

	public void setUpdatecycle(String updatecycle) {
		this.updatecycle = updatecycle;
	}

	public List<MtlChannelDef> getMtlChannelDefList() {
		return mtlChannelDefList;
	}

	public void setMtlChannelDefList(List<MtlChannelDef> mtlChannelDefList) {
		this.mtlChannelDefList = mtlChannelDefList;
	}

	public String getOrderPlanIds() {
		return orderPlanIds;
	}

	public void setOrderPlanIds(String orderPlanIds) {
		this.orderPlanIds = orderPlanIds;
	}

	public String getExcludePlanIds() {
		return excludePlanIds;
	}

	public void setExcludePlanIds(String excludePlanIds) {
		this.excludePlanIds = excludePlanIds;
	}

	public String getCreateUserName() {
		return createUserName;
	}

	public void setCreateUserName(String createUserName) {
		this.createUserName = createUserName;
	}

	public String getBasicEventTemplateId() {
		return basicEventTemplateId;
	}

	public void setBasicEventTemplateId(String basicEventTemplateId) {
		this.basicEventTemplateId = basicEventTemplateId;
	}

	public String getBussinessLableTemplateId() {
		return bussinessLableTemplateId;
	}

	public void setBussinessLableTemplateId(String bussinessLableTemplateId) {
		this.bussinessLableTemplateId = bussinessLableTemplateId;
	}

	public String getCustBaseMonth() {
		return custBaseMonth;
	}

	public void setCustBaseMonth(String custBaseMonth) {
		this.custBaseMonth = custBaseMonth;
	}

	public String getCustBaseDay() {
		return custBaseDay;
	}

	public void setCustBaseDay(String custBaseDay) {
		this.custBaseDay = custBaseDay;
	}

	public Integer getCustgroupNumber() {
		return custgroupNumber;
	}

	public void setCustgroupNumber(Integer custgroupNumber) {
		this.custgroupNumber = custgroupNumber;
	}

	public String getCustgroupType() {
		return custgroupType;
	}

	public void setCustgroupType(String custgroupType) {
		this.custgroupType = custgroupType;
	}

	public String getCustGroupName() {
		return custGroupName;
	}

	public void setCustGroupName(String custGroupName) {
		this.custGroupName = custGroupName;
	}

	public String getCampsegStatName() {
		return campsegStatName;
	}

	public void setCampsegStatName(String campsegStatName) {
		this.campsegStatName = campsegStatName;
	}

	public String getCampDrvIds() {
		return campDrvIds;
	}

	public void setCampDrvIds(String campDrvIds) {
		this.campDrvIds = campDrvIds;
	}

	public Integer getIsMy() {
		return isMy;
	}

	public void setIsMy(Integer isMy) {
		this.isMy = isMy;
	}

	public Boolean getIsZJ() {
		return isZJ;
	}

	public void setIsZJ(Boolean isZJ) {
		this.isZJ = isZJ;
	}

	public Integer getIsSelectMy() {
		return isSelectMy;
	}

	public void setIsSelectMy(Integer isSelectMy) {
		this.isSelectMy = isSelectMy;
	}

	public Integer getPageNum() {
		return pageNum;
	}

	public void setPageNum(Integer pageNum) {
		this.pageNum = pageNum;
	}

	public Short getIsSplitCustgroup() {
		return isSplitCustgroup;
	}

	public void setIsSplitCustgroup(Short isSplitCustgroup) {
		this.isSplitCustgroup = isSplitCustgroup;
	}

	// 甘肃增加营销指令 zhenyq3 2014-11-12 start
	private String exeContentType;// 营销用语类型
	private String campsegInstruct;// 营销指令
	// 甘肃增加营销指令 zhenyq3 2014-11-12 start

	// 是否场景模板
	private Integer isSceneTemplate;
	// 短信派发时限字段，用于限定渠道短信派发的时间
	private Integer sendTimeLimit;

	//场景来源 1-模板,2-活动
	private String sceneSourceFrom;
	//客户群反馈类型
	private String custEvelTypeId;
	
	//是否加挂热点业务字段
	private Short isMountHotPlan; 

	//派单时是否进行属地化识别，按策划人归属地过滤客户清单 0:否;1:是
	private Short isLocalFilter;
	
	//外呼渠道活动派单顺序
	private Short sendOrder; 
	
	//指令名称
	private String instruct;
	
	//是否按照客户群周期性发放
	private Integer isPeriodicity;
	
	
	private String pictureName;//产品图片名称
	private String linkedPicAdr;//产品图片链接地址
	
	
	
	public String getPictureName() {
		return pictureName;
	}

	public void setPictureName(String pictureName) {
		this.pictureName = pictureName;
	}

	public String getLinkedPicAdr() {
		return linkedPicAdr;
	}

	public void setLinkedPicAdr(String linkedPicAdr) {
		this.linkedPicAdr = linkedPicAdr;
	}
	
	public Integer getIsPeriodicity() {
		return isPeriodicity;
	}

	public void setIsPeriodicity(Integer isPeriodicity) {
		this.isPeriodicity = isPeriodicity;
	}
	//广告ids
	private String ad_ids;
	//广告名称
	private String ad_names;
	
	public String getInstruct() {
		return instruct;
	}

	public void setInstruct(String instruct) {
		this.instruct = instruct;
	}

	public Short getIsMountHotPlan() {
		return isMountHotPlan;
	}

	public void setIsMountHotPlan(Short isMountHotPlan) {
		this.isMountHotPlan = isMountHotPlan;
	}

	public String getCustEvelTypeId() {
		return custEvelTypeId;
	}

	public void setCustEvelTypeId(String custEvelTypeId) {
		this.custEvelTypeId = custEvelTypeId;
	}

	public String getSceneSourceFrom() {
		return sceneSourceFrom;
	}

	public void setSceneSourceFrom(String sceneSourceFrom) {
		this.sceneSourceFrom = sceneSourceFrom;
	}
	
	
	public Integer getIsSceneTemplate() {
		return isSceneTemplate;
	}

	public void setIsSceneTemplate(Integer isSceneTemplate) {
		this.isSceneTemplate = isSceneTemplate;
	}

	public Integer getSendTimeLimit() {
		return sendTimeLimit;
	}

	public void setSendTimeLimit(Integer sendTimeLimit) {
		this.sendTimeLimit = sendTimeLimit;
	}

	public String getExeContentType() {
		return exeContentType;
	}

	public void setExeContentType(String exeContentType) {
		this.exeContentType = exeContentType;
	}

	public String getCampsegInstruct() {
		return campsegInstruct;
	}

	public void setCampsegInstruct(String campsegInstruct) {
		this.campsegInstruct = campsegInstruct;
	}

	public Integer getIs_containFee() {
		return is_containFee;
	}

	public void setIs_containFee(Integer is_containFee) {
		this.is_containFee = is_containFee;
	}

	public String getCurrentUserId() {
		return currentUserId;
	}

	public void setCurrentUserId(String currentUserId) {
		this.currentUserId = currentUserId;
	}

	private String cepEventId; // 复杂事件ID
	
	private String eventRuleDesc;  //复杂事件描述

	private String drvDeptCode; // 驱动部门类型code_陕西

	public String getDrvDeptCode() {
		return drvDeptCode;
	}

	public void setDrvDeptCode(String drvDeptCode) {
		this.drvDeptCode = drvDeptCode;
	}

	public String getRuleIds() {
		return ruleIds;
	}

	public void setRuleIds(String ruleIds) {
		this.ruleIds = ruleIds;
	}

	public String getChannelName() {
		return channelName;
	}

	public void setChannelName(String channelName) {
		this.channelName = channelName;
	}

	public int getCustGroupNum() {
		return custGroupNum;
	}

	public void setCustGroupNum(int custGroupNum) {
		this.custGroupNum = custGroupNum;
	}

	public String getCustGroupAttrId() {
		return custGroupAttrId;
	}

	public void setCustGroupAttrId(String custGroupAttrId) {
		this.custGroupAttrId = custGroupAttrId;
	}

	private String execContent; // 辅助营销用于

	private String eventSourceId; // 外部事件源
	private List<McdCampsegPolicyRelation> policyList;// 规则对应策略集合

	public List<McdCampsegPolicyRelation> getPolicyList() {
		return policyList;
	}

	public void setPolicyList(List<McdCampsegPolicyRelation> policyList) {
		this.policyList = policyList;
	}

	public String getEventSourceId() {
		return eventSourceId;
	}

	public void setEventSourceId(String eventSourceId) {
		this.eventSourceId = eventSourceId;
	}

	public String getSystemId() {
		return systemId;
	}

	public void setSystemId(String systemId) {
		this.systemId = systemId;
	}

	public String getAvoidBotherTypeIds() {
		return avoidBotherTypeIds;
	}

	public void setAvoidBotherTypeIds(String avoidBotherTypeIds) {
		this.avoidBotherTypeIds = avoidBotherTypeIds;
	}

	public String getEventActiveTempletId() {
		return eventActiveTempletId;
	}

	public void setEventActiveTempletId(String eventActiveTempletId) {
		this.eventActiveTempletId = eventActiveTempletId;
	}

	private String keywords;// 关键字

	public String getKeywords() {
		return keywords;
	}

	public void setKeywords(String keywords) {
		this.keywords = keywords;
	}

	public String getCampDrvName() {
		return campDrvName;
	}

	public void setCampDrvName(String campDrvName) {
		this.campDrvName = campDrvName;
	}

	public boolean isTest() {
		return isTest;
	}

	public void setTest(boolean isTest) {
		this.isTest = isTest;
	}

	public String getAvoidTimeRange() {
		return avoidTimeRange;
	}

	public void setAvoidTimeRange(String avoidTimeRange) {
		this.avoidTimeRange = avoidTimeRange;
	}

	public String getInteractionRule() {
		return interactionRule;
	}

	public void setInteractionRule(String interactionRule) {
		this.interactionRule = interactionRule;
	}

	public String getInteractionView() {
		return interactionView;
	}

	public void setInteractionView(String interactionView) {
		this.interactionView = interactionView;
	}

	public Integer getIsRelativeExecTime() {
		return isRelativeExecTime;
	}

	public void setIsRelativeExecTime(Integer isRelativeExecTime) {
		this.isRelativeExecTime = isRelativeExecTime;
	}

	public Integer getCampWaveDelayFrom() {
		return campWaveDelayFrom;
	}

	public void setCampWaveDelayFrom(Integer campWaveDelayFrom) {
		this.campWaveDelayFrom = campWaveDelayFrom;
	}

	public Integer getCampWaveDelayTo() {
		return campWaveDelayTo;
	}

	public void setCampWaveDelayTo(Integer campWaveDelayTo) {
		this.campWaveDelayTo = campWaveDelayTo;
	}

	public Integer getIsWaitFrontOver() {
		return isWaitFrontOver;
	}

	public void setIsWaitFrontOver(Integer isWaitFrontOver) {
		this.isWaitFrontOver = isWaitFrontOver;
	}

	public String getActiveTempletId() {
		return activeTempletId;
	}

	public void setActiveTempletId(String activeTempletId) {
		this.activeTempletId = activeTempletId;
	}

	public String getCustListTabName() {
		return custListTabName;
	}

	public void setCustListTabName(String custListTabName) {
		this.custListTabName = custListTabName;
	}

	public Integer getWaveContactType() {
		return waveContactType;
	}

	public void setWaveContactType(Integer waveContactType) {
		this.waveContactType = waveContactType;
	}

	public Integer getWaveContactCount() {
		return waveContactCount;
	}

	public void setWaveContactCount(Integer waveContactCount) {
		this.waveContactCount = waveContactCount;
	}

	public Integer getContactCount() {
		return contactCount;
	}

	public void setContactCount(Integer contactCount) {
		this.contactCount = contactCount;
	}

	public Integer getContainOutProvince() {
		return containOutProvince;
	}

	public void setContainOutProvince(Integer containOutProvince) {
		this.containOutProvince = containOutProvince;
	}

	public Integer getSupportWifi() {
		return supportWifi;
	}

	public void setSupportWifi(Integer supportWifi) {
		this.supportWifi = supportWifi;
	}

	public String getSubCampDrvId() {
		return subCampDrvId;
	}

	public void setSubCampDrvId(String subCampDrvId) {
		this.subCampDrvId = subCampDrvId;
	}

	public Short getCampsegTypeId() {
		return campsegTypeId;
	}

	public void setCampsegTypeId(Short campsegTypeId) {
		this.campsegTypeId = campsegTypeId;
	}

	public String getFilePath() {
		return filePath;
	}

	public void setFilePath(String filePath) {
		this.filePath = filePath;
	}

	/**
	 * @return createType
	 */
	public String getCreateType() {
		return createType;
	}

	/**
	 * @param createType
	 *            要设置的 createType
	 */
	public void setCreateType(String createType) {
		this.createType = createType;
	}

	/**
	 * @return flowId
	 */
	public String getFlowId() {
		return flowId;
	}

	/**
	 * @param flowId
	 *            要设置的 flowId
	 */
	public void setFlowId(String flowId) {
		this.flowId = flowId;
	}

	/**
	 * @return promotionTypeId
	 */
	public String getPromotionTypeId() {
		return promotionTypeId;
	}

	/**
	 * @param promotionTypeId
	 *            要设置的 promotionTypeId
	 */
	public void setPromotionTypeId(String promotionTypeId) {
		this.promotionTypeId = promotionTypeId;
	}

	public Set getCampsegProgress() {
		return campsegProgress;
	}

	public void setCampsegProgress(Set campsegProgress) {
		this.campsegProgress = campsegProgress;
	}

	// Constructors

	/** default constructor */
	public MtlCampSeginfo() {
	}

	/** minimal constructor */
	public MtlCampSeginfo(Date createTime) {
		this.createTime = createTime;
	}

	// Property accessors

	public String getCampsegId() {
		return campsegId;
	}

	public void setCampsegId(String campsegId) {
		this.campsegId = campsegId;
	}

	public String getStartDate() {
		return startDate;
	}

	public void setStartDate(String startDate) {
		this.startDate = startDate;
	}

	public String getEndDate() {
		return endDate;
	}

	public void setEndDate(String endDate) {
		this.endDate = endDate;
	}

	public Integer getTargerUserNums() {
		return targerUserNums;
	}

	public void setTargerUserNums(Integer targerUserNums) {
		this.targerUserNums = targerUserNums;
	}

	public Integer getContactedUserNums() {
		return contactedUserNums;
	}

	public void setContactedUserNums(Integer contactedUserNums) {
		this.contactedUserNums = contactedUserNums;
	}

	public Integer getContactOkuserNums() {
		return contactOkuserNums;
	}

	public void setContactOkuserNums(Integer contactOkuserNums) {
		this.contactOkuserNums = contactOkuserNums;
	}

	public Integer getReceivedOkuserNums() {
		return receivedOkuserNums;
	}

	public void setReceivedOkuserNums(Integer receivedOkuserNums) {
		this.receivedOkuserNums = receivedOkuserNums;
	}

	public Short getCampsegStatId() {
		return campsegStatId;
	}

	public void setCampsegStatId(Short campsegStatId) {
		this.campsegStatId = campsegStatId;
	}

	public String getCampId() {
		return campId;
	}

	public void setCampId(String campId) {
		this.campId = campId;
	}

	public Short getApproveResult() {
		return approveResult;
	}

	public void setApproveResult(Short approveResult) {
		this.approveResult = approveResult;
	}

	public Short getApproveReceiveNums() {
		return approveReceiveNums;
	}

	public void setApproveReceiveNums(Short approveReceiveNums) {
		this.approveReceiveNums = approveReceiveNums;
	}

	public String getCampsegNo() {
		return campsegNo;
	}

	public void setCampsegNo(String campsegNo) {
		this.campsegNo = campsegNo;
	}

	public String getCampsegName() {
		return campsegName;
	}

	public void setCampsegName(String campsegName) {
		this.campsegName = campsegName;
	}

	public Date getCreateTime() {
		return createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public String getCampsegDesc() {
		return campsegDesc;
	}

	public void setCampsegDesc(String campsegDesc) {
		this.campsegDesc = campsegDesc;
	}

	public Integer getCampsegContrastUsers() {
		return campsegContrastUsers;
	}

	public void setCampsegContrastUsers(Integer campsegContrastUsers) {
		this.campsegContrastUsers = campsegContrastUsers;
	}

	public Integer getCampsegMaxUsers() {
		return campsegMaxUsers;
	}

	public void setCampsegMaxUsers(Integer campsegMaxUsers) {
		this.campsegMaxUsers = campsegMaxUsers;
	}

	public Set getCampsegAttachs() {
		return campsegAttachs;
	}

	public void setCampsegAttachs(Set campsegAttachs) {
		this.campsegAttachs = campsegAttachs;
	}

	public String getSrcdataDate() {
		return srcdataDate;
	}

	public void setSrcdataDate(String srcdataDate) {
		this.srcdataDate = srcdataDate;
	}

	public Integer getContrastUserNums() {
		return contrastUserNums;
	}

	public void setContrastUserNums(Integer contrastUserNums) {
		this.contrastUserNums = contrastUserNums;
	}

	public String getEvaluateComment() {
		return evaluateComment;
	}

	public void setEvaluateComment(String evaluateComment) {
		this.evaluateComment = evaluateComment;
	}

	public Short getCampsegContactFlag() {
		return campsegContactFlag;
	}

	public void setCampsegContactFlag(Short campsegContactFlag) {
		this.campsegContactFlag = campsegContactFlag;
	}

	/**
	 * @return publicizeCombId
	 */
	public String getPublicizeCombId() {
		return publicizeCombId;
	}

	/**
	 * @param publicizeCombId
	 *            要设置的 publicizeCombId
	 */
	public void setPublicizeCombId(String publicizeCombId) {
		this.publicizeCombId = publicizeCombId;
	}

	/**
	 * @return createUserid
	 */
	public String getCreateUserid() {
		return createUserid;
	}

	/**
	 * @param createUserid
	 *            要设置的 createUserid
	 */
	public void setCreateUserid(String createUserid) {
		this.createUserid = createUserid;
	}

	/**
	 * @return approveFlowid
	 */
	public String getApproveFlowid() {
		return approveFlowid;
	}

	/**
	 * @param approveFlowid
	 *            要设置的 approveFlowid
	 */
	public void setApproveFlowid(String approveFlowid) {
		this.approveFlowid = approveFlowid;
	}

	/**
	 * @return cityId
	 */
	public String getCityId() {
		return cityId;
	}

	/**
	 * @param cityId
	 *            要设置的 cityId
	 */
	public void setCityId(String cityId) {
		this.cityId = cityId;
	}

	/**
	 * @return confirmFlag
	 */
	public Short getConfirmFlag() {
		return confirmFlag;
	}

	/**
	 * @param confirmFlag
	 *            要设置的 confirmFlag
	 */
	public void setConfirmFlag(Short confirmFlag) {
		this.confirmFlag = confirmFlag;
	}

	public String getToStartDate() {
		return toStartDate;
	}

	public void setToStartDate(String toStartDate) {
		this.toStartDate = toStartDate;
	}

	public String getToEndDate() {
		return toEndDate;
	}

	public void setToEndDate(String toEndDate) {
		this.toEndDate = toEndDate;
	}

	/**
	 * @return deptId
	 */
	public Integer getDeptId() {
		return deptId;
	}

	/**
	 * @param deptId
	 *            要设置的 deptId
	 */
	public void setDeptId(Integer deptId) {
		this.deptId = deptId;
	}

	public String getCampName() {
		return campName;
	}

	public void setCampName(String campName) {
		this.campName = campName;
	}

	public Set getCampsegUsersegs() {
		return campsegUsersegs;
	}

	public void setCampsegUsersegs(Set campsegUsersegs) {
		this.campsegUsersegs = campsegUsersegs;
	}

	/**
	 * @return campDrvId
	 */
	public Short getCampDrvId() {
		return campDrvId;
	}

	/**
	 * @param campDrvId
	 *            要设置的 campDrvId
	 */
	public void setCampDrvId(Short campDrvId) {
		this.campDrvId = campDrvId;
	}

	/**
	 * @return campPriId
	 */
	public Short getCampPriId() {
		return campPriId;
	}

	/**
	 * @param campPriId
	 *            要设置的 campPriId
	 */
	public void setCampPriId(Short campPriId) {
		this.campPriId = campPriId;
	}

	/**
	 * @return planExecId
	 */
	public String getPlanExecId() {
		return planExecId;
	}

	/**
	 * @param planExecId
	 *            要设置的 planExecId
	 */
	public void setPlanExecId(String planExecId) {
		this.planExecId = planExecId;
	}

	public Integer getCampsegContactUsernums() {
		return CampsegContactUsernums;
	}

	public void setCampsegContactUsernums(Integer campsegContactUsernums) {
		CampsegContactUsernums = campsegContactUsernums;
	}

	/**
	 * @return scenesId
	 */
	public String getScenesId() {
		return scenesId;
	}

	/**
	 * @param scenesId
	 *            要设置的 scenesId
	 */
	public void setScenesId(String scenesId) {
		this.scenesId = scenesId;
	}

	public String getExecuteUser() {
		return executeUser;
	}

	public void setExecuteUser(String executeUser) {
		this.executeUser = executeUser;
	}

	public Short getFormatMessFlag() {
		return formatMessFlag;
	}

	public void setFormatMessFlag(Short formatMessFlag) {
		this.formatMessFlag = formatMessFlag;
	}

	public String getTestProductNo() {
		return testProductNo;
	}

	public void setTestProductNo(String testProductNo) {
		this.testProductNo = testProductNo;
	}

	public String getChannelExtendInfo() {
		return channelExtendInfo;
	}

	public void setChannelExtendInfo(String channelExtendInfo) {
		this.channelExtendInfo = channelExtendInfo;
	}

	public Short getIsTemplate() {
		return isTemplate;
	}

	public void setIsTemplate(Short isTemplate) {
		this.isTemplate = isTemplate;
	}

	public Integer getSendtimeDelay() {
		return sendtimeDelay;
	}

	public void setSendtimeDelay(Integer sendtimeDelay) {
		this.sendtimeDelay = sendtimeDelay;
	}

	public String getTimeRange() {
		return timeRange;
	}

	public void setTimeRange(String timeRange) {
		this.timeRange = timeRange;
	}

	public String getSceneType() {
		return sceneType;
	}

	public void setSceneType(String sceneType) {
		this.sceneType = sceneType;
	}

	public String getTimeInterval() {
		return timeInterval;
	}

	public void setTimeInterval(String timeInterval) {
		this.timeInterval = timeInterval;
	}

	public Integer getIsFromVgopFlag() {
		return isFromVgopFlag;
	}

	public void setIsFromVgopFlag(Integer isFromVgopFlag) {
		this.isFromVgopFlag = isFromVgopFlag;
	}

	public String getIsDelSnap() {
		return isDelSnap;
	}

	public void setIsDelSnap(String isDelSnap) {
		this.isDelSnap = isDelSnap;
	}

	public String getBusshallId() {
		return busshallId;
	}

	public void setBusshallId(String busshallId) {
		this.busshallId = busshallId;
	}

	public String getCampsegBussiCode() {
		return campsegBussiCode;
	}

	public void setCampsegBussiCode(String campsegBussiCode) {
		this.campsegBussiCode = campsegBussiCode;
	}

	public Integer getContactType() {
		return contactType;
	}

	public void setContactType(Integer contactType) {
		this.contactType = contactType;
	}

	public String getCampsegPid() {
		return campsegPid;
	}

	public void setCampsegPid(String campsegPid) {
		this.campsegPid = campsegPid;
	}

	public Integer getCampClass() {
		return campClass;
	}

	public void setCampClass(Integer campClass) {
		this.campClass = campClass;
	}

	public String getWaveConId() {
		return waveConId;
	}

	public void setWaveConId(String waveConId) {
		this.waveConId = waveConId;
	}

	public Integer getCampWaveDelay() {
		return campWaveDelay;
	}

	public void setCampWaveDelay(Integer campWaveDelay) {
		this.campWaveDelay = campWaveDelay;
	}

	public String getPlanId() {
		return planId;
	}

	public void setPlanId(String planId) {
		this.planId = planId;
	}

	public Integer getExecuteStatus() {
		return executeStatus;
	}

	public void setExecuteStatus(Integer executeStatus) {
		this.executeStatus = executeStatus;
	}

	public String getAreaId() {
		return areaId;
	}

	public void setAreaId(String areaId) {
		this.areaId = areaId;
	}

	public String getAbsoluteDates() {
		return absoluteDates;
	}

	public void setAbsoluteDates(String absoluteDates) {
		this.absoluteDates = absoluteDates;
	}

	public String getChannelCampContent() {
		return channelCampContent;
	}

	public void setChannelCampContent(String channelCampContent) {
		this.channelCampContent = channelCampContent;
	}

	public String getCustgroupId() {
		return custgroupId;
	}

	public void setCustgroupId(String custgroupId) {
		this.custgroupId = custgroupId;
	}

	public String getChannelId() {
		return channelId;
	}

	public void setChannelId(String channelId) {
		this.channelId = channelId;
	}

	public String getChannelTypeId() {
		return channelTypeId;
	}

	public void setChannelTypeId(String channelTypeId) {
		this.channelTypeId = channelTypeId;
	}

	public String getCurrentTaskId() {
		return currentTaskId;
	}

	public void setCurrentTaskId(String currentTaskId) {
		this.currentTaskId = currentTaskId;
	}

	public String getRejectCampsegIds() {
		return rejectCampsegIds;
	}

	public void setRejectCampsegIds(String rejectCampsegIds) {
		this.rejectCampsegIds = rejectCampsegIds;
	}

	public String getAreaName() {
		return areaName;
	}

	public void setAreaName(String areaName) {
		this.areaName = areaName;
	}

	public String getConfirmState() {
		return confirmState;
	}

	public void setConfirmState(String confirmState) {
		this.confirmState = confirmState;
	}

	public String getConfirmUserId() {
		return confirmUserId;
	}

	public void setConfirmUserId(String confirmUserId) {
		this.confirmUserId = confirmUserId;
	}

	public String getTestNumber() {
		return testNumber;
	}

	public void setTestNumber(String testNumber) {
		this.testNumber = testNumber;
	}

	public String getExecContent() {
		return execContent;
	}

	public void setExecContent(String execContent) {
		this.execContent = execContent;
	}

	public String getCepEventId() {
		return cepEventId;
	}

	public void setCepEventId(String cepEventId) {
		this.cepEventId = cepEventId;
	}

	public String getFirstApproveUserId() {
		return firstApproveUserId;
	}

	public void setFirstApproveUserId(String firstApproveUserId) {
		this.firstApproveUserId = firstApproveUserId;
	}

	public String getRecommendDesc() {
		return recommendDesc;
	}

	public void setRecommendDesc(String recommendDesc) {
		this.recommendDesc = recommendDesc;
	}

	public String getOnlineServiceUrl() {
		return onlineServiceUrl;
	}

	public void setOnlineServiceUrl(String onlineServiceUrl) {
		this.onlineServiceUrl = onlineServiceUrl;
	}

	/**
	 * 客户群类型(0:无 ,1:客户群 2:来自其他活动规则的反馈)
	 * 
	 * @return
	 */
	public Integer getTargetCustType() {
		return targetCustType;
	}

	/**
	 * 客户群类型(0:无 ,1:客户群 2:来自其他活动规则的反馈)
	 * 
	 * @param targetCustType
	 */
	public void setTargetCustType(Integer targetCustType) {
		this.targetCustType = targetCustType;
	}

	/**
	 * 来自其他活动规则的反馈
	 * 
	 * @return
	 */
	public McdTargetCustFeedback getMcdTargetCustFeedback() {
		return mcdTargetCustFeedback;
	}

	/**
	 * 来自其他活动规则的反馈
	 * 
	 * @param mcdTargetCustFeedback
	 */
	public void setMcdTargetCustFeedback(
			McdTargetCustFeedback mcdTargetCustFeedback) {
		this.mcdTargetCustFeedback = mcdTargetCustFeedback;
	}

	public String getSiteCategoryIdClassId() {
		return siteCategoryIdClassId;
	}

	public void setSiteCategoryIdClassId(String siteCategoryIdClassId) {
		this.siteCategoryIdClassId = siteCategoryIdClassId;
	}

	public int getSplitCampSegInfo() {
		return splitCampSegInfo;
	}

	public void setSplitCampSegInfo(int splitCampSegInfo) {
		this.splitCampSegInfo = splitCampSegInfo;
	}

	public Short getIsLocalFilter() {
		return isLocalFilter;
	}

	public void setIsLocalFilter(Short isLocalFilter) {
		this.isLocalFilter = isLocalFilter;
	}

	public Short getSendOrder() {
		return sendOrder;
	}

	public void setSendOrder(Short sendOrder) {
		this.sendOrder = sendOrder;
	}

	public String getAd_ids() {
		return ad_ids;
	}

	public void setAd_ids(String ad_ids) {
		this.ad_ids = ad_ids;
	}

	public String getAd_names() {
		return ad_names;
	}

	public void setAd_names(String ad_names) {
		this.ad_names = ad_names;
	}

	public String getApproveResultDesc() {
		return approveResultDesc;
	}

	public void setApproveResultDesc(String approveResultDesc) {
		this.approveResultDesc = approveResultDesc;
	}

	public String getSelectTempletId() {
		return selectTempletId;
	}

	public void setSelectTempletId(String selectTempletId) {
		this.selectTempletId = selectTempletId;
	}

	public String getInitCustListTab() {
		return initCustListTab;
	}

	public void setInitCustListTab(String initCustListTab) {
		this.initCustListTab = initCustListTab;
	}

	public String getEventRuleDesc() {
		return eventRuleDesc;
	}

	public void setEventRuleDesc(String eventRuleDesc) {
		this.eventRuleDesc = eventRuleDesc;
	}

	public MtlChannelDefCall getMtlChannelDefCall() {
		return mtlChannelDefCall;
	}

	public void setMtlChannelDefCall(MtlChannelDefCall mtlChannelDefCall) {
		this.mtlChannelDefCall = mtlChannelDefCall;
	}
	
	
	
}
