package com.asiainfo.biapp.mcd.model;

import com.asiainfo.biapp.mcd.constants.MpmCONST;
import com.asiainfo.biapp.mcd.util.MpmCache;

/**
 * MtlCampDatasrcColumn generated by MyEclipse - Hibernate Tools
 */

public class MtlCampDatasrcColumn implements java.io.Serializable {

	// Fields    

	private MtlCampDatasrcColumnId id = new MtlCampDatasrcColumnId();

	private String columnCname;

	private String columnClass;

	private String columnFlag;

	private String columnDesc;

	//因为表类型和表状态没有维表,用于展现标识描述信息
	private String columnCtype;

	private String columnCclass;

	private String columnCflag;

	private String columnDatatype;

	private String beforeColumnName;

	private Short columnStatus;

	private Short columnCStatus;

	// Constructors

	/** default constructor */
	public MtlCampDatasrcColumn() {
	}

	/** minimal constructor */
	public MtlCampDatasrcColumn(MtlCampDatasrcColumnId id) {
		this.id = id;
	}

	/** full constructor */
	public MtlCampDatasrcColumn(MtlCampDatasrcColumnId id, String columnCname, String columnClass, String columnFlag, String columnDesc) {
		this.id = id;
		this.columnCname = columnCname;
		this.columnClass = columnClass;
		this.columnFlag = columnFlag;
		this.columnDesc = columnDesc;
	}

	// Property accessors

	public MtlCampDatasrcColumnId getId() {
		return this.id;
	}

	public void setId(MtlCampDatasrcColumnId id) {
		this.id = id;
	}

	public String getColumnCname() {
		return this.columnCname;
	}

	public void setColumnCname(String columnCname) {
		this.columnCname = columnCname;
	}

	public String getColumnClass() {
		return this.columnClass;
	}

	public void setColumnClass(String columnClass) {
		this.columnClass = columnClass;
	}

	public String getColumnFlag() {
		return this.columnFlag;
	}

	public void setColumnFlag(String columnFlag) {
		this.columnFlag = columnFlag;
	}

	public String getColumnDesc() {
		return this.columnDesc;
	}

	public void setColumnDesc(String columnDesc) {
		this.columnDesc = columnDesc;
	}

	public String getColumnDatatype() {
		return this.columnDatatype;
	}

	public void setColumnDatatype(String columnDatatype) {
		this.columnDatatype = columnDatatype;
	}

	public void setBeforeColumnName(String beforeColumnName) {
		this.beforeColumnName = beforeColumnName;
	}

	public String getBeforeColumnName() {
		return this.beforeColumnName;
	}

	public String getColumnCtype() {
		String columntype = id.getColumnType();
		return MpmCache.getInstance().getNameByTypeAndKey(MpmCONST.MPM_DS_COLUMN_TYPE, columntype);
	}

	public String getColumnCclass() {
		return MpmCache.getInstance().getNameByTypeAndKey(MpmCONST.BASE_TABLE_COLUMN_TYPE, this.columnClass);
	}

	public String getColumnCflag() {
		return MpmCache.getInstance().getNameByTypeAndKey(MpmCONST.SOURCE_TABLE_COLUMN_FLAG, this.columnFlag);
	}

	public Short getColumnStatus() {
		return columnStatus;
	}

	public void setColumnStatus(Short columnStatus) {
		this.columnStatus = columnStatus;
	}

	public String getColumnCStatus() {
		if (this.columnStatus == null)
			return "";
		return MpmCache.getInstance().getNameByTypeAndKey(MpmCONST.MPM_DATASRC_COLUMN_STATUS, this.columnStatus.toString());
	}
}
