package com.asiainfo.biapp.mcd.model;

/**
 * MtlCampsegCustGroupId generated by MyEclipse Persistence Tools
 */

public class MtlCampsegCustGroupId implements java.io.Serializable {

	// Fields

	private String campsegId;

	private short custGroupUsedType;

	// Constructors

	/** default constructor */
	public MtlCampsegCustGroupId() {
	}

	/** full constructor */
	public MtlCampsegCustGroupId(String campsegId, short custGroupUsedType) {
		this.campsegId = campsegId;
		this.custGroupUsedType = custGroupUsedType;
	}

	// Property accessors

	public String getCampsegId() {
		return this.campsegId;
	}

	public void setCampsegId(String campsegId) {
		this.campsegId = campsegId;
	}

	public short getCustGroupUsedType() {
		return this.custGroupUsedType;
	}

	public void setCustGroupUsedType(short custGroupUsedType) {
		this.custGroupUsedType = custGroupUsedType;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MtlCampsegCustGroupId))
			return false;
		MtlCampsegCustGroupId castOther = (MtlCampsegCustGroupId) other;

		return ((this.getCampsegId() == castOther.getCampsegId()) || (this.getCampsegId() != null && castOther.getCampsegId() != null && this.getCampsegId().equals(castOther.getCampsegId()))) && (this.getCustGroupUsedType() == castOther.getCustGroupUsedType());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCampsegId() == null ? 0 : this.getCampsegId().hashCode());
		result = 37 * result + this.getCustGroupUsedType();
		return result;
	}

}
