package com.asiainfo.biapp.mcd.model;

import java.util.Date;
import java.util.Set;

/**
 * MtlCampBaseinfo generated by MyEclipse - Hibernate Tools
 */

public class MtlCampBaseinfo implements java.io.Serializable {

	// Fields    

	private String campId;

	private String startDate;

	private String endDate;

	private String createUserid;

	private String cityId;

	private String campName;

	private String campsegName;

	private Date createDate;

	private Short campReplayStatus;

	private Short statusChgType;

	private String campDesc;

	private String campStrageDesc;

	private String objectiveDesc;

	private Short campPriId;

	private Short campDrvId;
	
	private String campDrvName;

	private Short campStatus;

	private Integer deptId;

	private String promoId;

	private String evaluateComment;

	private Short confirmFlag;
	private Integer brandId;
	private Short existVipCustFlag;

	private Short approveResult; //审批结果

	private Short approveReceiveNums;//审批次数

	private String campsegStatId; //状态

	private String toStartDate; //至 开始日期

	private String toEndDate; //至 结束日期	

	private String approveFlowid;

	private Double guessTotalCost;

	private Double guessTotalCustNum;

	private String queryCreateUserid;

	private String[] channelType;//营销案营销渠道

	private String campCityName;
	private String campCityId;

	private String channelTypeName;

	private Set campSegs;

	private Set campIndis;

	private Set campPlans;

	private Set campAttachs;

	private String campDrvIdStr;

	private String partnerId;

	//add by YangQ
	//当前使用查询功能的用户ID
	protected String userId;

	//当前用户所属角色的地市权限（格式如:'cityId1','cityId2','cityId3'...）
	protected String userCityPolicys;

	private Short serviceType;
	private Short hodCcoFlag;
	private String subCampDrvId;

	private String campIds;
	// 是否是模板
	private Short isTemplate;

	//批件文号
	private String campApproveCode;
	//是否含经费
	private Short isContainFee;
	//总成本投入
	private Float totalCost;
	//联系人
	private String contact;
	//联系电话
	private String telNumber;

	//成本
	private String costValues;
	//成本类型
	private String costCodes;
	//附件ID
	private String attachIds;
	//附件名称
	private String attachNames;
	//关键字
	private String keywords;
	//系统ID
	private String systemId;
	//msm活动Id
	private String msmCampsegId;
	
	private String firstApproveUserId;

	public String getCampDrvName() {
		return campDrvName;
	}

	public void setCampDrvName(String campDrvName) {
		this.campDrvName = campDrvName;
	}

	public String getSystemId() {
		return systemId;
	}

	public void setSystemId(String systemId) {
		this.systemId = systemId;
	}

	public String getKeywords() {
		return keywords;
	}

	public void setKeywords(String keywords) {
		this.keywords = keywords;
	}

	public String getCampCityId() {
		return campCityId;
	}

	public void setCampCityId(String campCityId) {
		this.campCityId = campCityId;
	}

	public String getCostValues() {
		return costValues;
	}

	public void setCostValues(String costValues) {
		this.costValues = costValues;
	}

	public String getCostCodes() {
		return costCodes;
	}

	public void setCostCodes(String costCodes) {
		this.costCodes = costCodes;
	}

	public String getAttachIds() {
		return attachIds;
	}

	public void setAttachIds(String attachIds) {
		this.attachIds = attachIds;
	}

	public String getAttachNames() {
		return attachNames;
	}

	public void setAttachNames(String attachNames) {
		this.attachNames = attachNames;
	}

	public String getSubCampDrvId() {
		return subCampDrvId;
	}

	public void setSubCampDrvId(String subCampDrvId) {
		this.subCampDrvId = subCampDrvId;
	}

	public Short getHodCcoFlag() {
		return hodCcoFlag;
	}

	public void setHodCcoFlag(Short hodCcoFlag) {
		this.hodCcoFlag = hodCcoFlag;
	}

	public Short getServiceType() {
		return serviceType;
	}

	public void setServiceType(Short serviceType) {
		this.serviceType = serviceType;
	}

	public String getUserCityPolicys() {
		return userCityPolicys;
	}

	public void setUserCityPolicys(String userCityPolicys) {
		this.userCityPolicys = userCityPolicys;
	}

	public String getUserId() {
		return userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	// Constructors

	/** default constructor */
	public MtlCampBaseinfo() {
	}

	/** minimal constructor */
	public MtlCampBaseinfo(Date createDate) {
		this.createDate = createDate;
	}

	// Property accessors

	public String getCampId() {
		return this.campId;
	}

	public void setCampId(String campId) {
		this.campId = campId;
	}

	public String getStartDate() {
		return this.startDate;
	}

	public void setStartDate(String startDate) {
		this.startDate = startDate;
	}

	public String getEndDate() {
		return this.endDate;
	}

	public void setEndDate(String endDate) {
		this.endDate = endDate;
	}

	public String getCampIds() {
		return campIds;
	}

	public void setCampIds(String campIds) {
		this.campIds = campIds;
	}

	public String getCreateUserid() {
		return this.createUserid;
	}

	public void setCreateUserid(String createUserid) {
		this.createUserid = createUserid;
	}

	public String getCityId() {
		return this.cityId;
	}

	public void setCityId(String cityId) {
		this.cityId = cityId;
	}

	public String getCampName() {
		return this.campName;
	}

	public void setCampName(String campName) {
		this.campName = campName;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Short getCampReplayStatus() {
		return this.campReplayStatus;
	}

	public void setCampReplayStatus(Short campReplayStatus) {
		this.campReplayStatus = campReplayStatus;
	}

	public Short getStatusChgType() {
		return this.statusChgType;
	}

	public void setStatusChgType(Short statusChgType) {
		this.statusChgType = statusChgType;
	}

	public String getCampDesc() {
		return this.campDesc;
	}

	public void setCampDesc(String campDesc) {
		this.campDesc = campDesc;
	}

	public String getCampStrageDesc() {
		return this.campStrageDesc;
	}

	public void setCampStrageDesc(String campStrageDesc) {
		this.campStrageDesc = campStrageDesc;
	}

	public String getObjectiveDesc() {
		return this.objectiveDesc;
	}

	public void setObjectiveDesc(String objectiveDesc) {
		this.objectiveDesc = objectiveDesc;
	}

	public Short getCampPriId() {
		return this.campPriId;
	}

	public void setCampPriId(Short campPriId) {
		this.campPriId = campPriId;
	}

	public Short getCampDrvId() {
		return this.campDrvId;
	}

	public void setCampDrvId(Short campDrvId) {
		this.campDrvId = campDrvId;
	}

	public Short getCampStatus() {
		return this.campStatus;
	}

	public void setCampStatus(Short campStatus) {
		this.campStatus = campStatus;
	}

	public Integer getDeptId() {
		return this.deptId;
	}

	public void setDeptId(Integer deptId) {
		this.deptId = deptId;
	}

	public Set getCampSegs() {
		return campSegs;
	}

	public void setCampSegs(Set campSegs) {
		this.campSegs = campSegs;
	}

	public Set getCampIndis() {
		return campIndis;
	}

	public void setCampIndis(Set campIndis) {
		this.campIndis = campIndis;
	}

	public Set getCampPlans() {
		return campPlans;
	}

	public void setCampPlans(Set campPlans) {
		this.campPlans = campPlans;
	}

	public Set getCampAttachs() {
		return campAttachs;
	}

	public void setCampAttachs(Set campAttachs) {
		this.campAttachs = campAttachs;
	}

	public String getToStartDate() {
		return toStartDate;
	}

	public void setToStartDate(String toStartDate) {
		this.toStartDate = toStartDate;
	}

	public String getToEndDate() {
		return toEndDate;
	}

	public void setToEndDate(String toEndDate) {
		this.toEndDate = toEndDate;
	}

	public java.lang.Short getApproveResult() {
		return approveResult;
	}

	public void setApproveResult(java.lang.Short approveResult) {
		this.approveResult = approveResult;
	}

	public String getCampsegStatId() {
		return campsegStatId;
	}

	public void setCampsegStatId(String campsegStatId) {
		this.campsegStatId = campsegStatId;
	}

	public String getPromoId() {
		return promoId;
	}

	public void setPromoId(String promoId) {
		this.promoId = promoId;
	}

	public String getEvaluateComment() {
		return evaluateComment;
	}

	public void setEvaluateComment(String evaluateComment) {
		this.evaluateComment = evaluateComment;
	}

	/**
	 * @return approveFlowid
	 */
	public String getApproveFlowid() {
		return approveFlowid;
	}

	/**
	 * @param approveFlowid 要设置的 approveFlowid
	 */
	public void setApproveFlowid(String approveFlowid) {
		this.approveFlowid = approveFlowid;
	}

	/**
	 * @return guessTotalCost
	 */
	public Double getGuessTotalCost() {
		return guessTotalCost;
	}

	/**
	 * @param guessTotalCost 要设置的 guessTotalCost
	 */
	public void setGuessTotalCost(Double guessTotalCost) {
		this.guessTotalCost = guessTotalCost;
	}

	/**
	 * @return guessTotalCustNum
	 */
	public Double getGuessTotalCustNum() {
		return guessTotalCustNum;
	}

	/**
	 * @param guessTotalCustNum 要设置的 guessTotalCustNum
	 */
	public void setGuessTotalCustNum(Double guessTotalCustNum) {
		this.guessTotalCustNum = guessTotalCustNum;
	}

	/**
	 * @return campsegName
	 */
	public String getCampsegName() {
		return campsegName;
	}

	/**
	 * @param campsegName 要设置的 campsegName
	 */
	public void setCampsegName(String campsegName) {
		this.campsegName = campsegName;
	}

	/**
	 * @return queryCreateUserid
	 */
	public String getQueryCreateUserid() {
		return queryCreateUserid;
	}

	/**
	 * @param queryCreateUserid 要设置的 queryCreateUserid
	 */
	public void setQueryCreateUserid(String queryCreateUserid) {
		this.queryCreateUserid = queryCreateUserid;
	}

	/**
	 * @return campCityName
	 */
	public String getCampCityName() {
		return campCityName;
	}

	/**
	 * @param campCityName 要设置的 campCityName
	 */
	public void setCampCityName(String campCityName) {
		this.campCityName = campCityName;
	}

	/**
	 * @return channelType
	 */
	public String[] getChannelType() {
		return channelType;
	}

	/**
	 * @param channelType 要设置的 channelType
	 */
	public void setChannelType(String[] channelType) {
		this.channelType = channelType;
	}

	/**
	 * @return approveReceiveNums
	 */
	public Short getApproveReceiveNums() {
		return approveReceiveNums;
	}

	/**
	 * @param approveReceiveNums 要设置的 approveReceiveNums
	 */
	public void setApproveReceiveNums(Short approveReceiveNums) {
		this.approveReceiveNums = approveReceiveNums;
	}

	/**
	 * @return channelTypeName
	 */
	public String getChannelTypeName() {
		return channelTypeName;
	}

	/**
	 * @param channelTypeName 要设置的 channelTypeName
	 */
	public void setChannelTypeName(String channelTypeName) {
		this.channelTypeName = channelTypeName;
	}

	public Short getConfirmFlag() {
		return confirmFlag;
	}

	public void setConfirmFlag(Short confirmFlag) {
		this.confirmFlag = confirmFlag;
	}

	public Integer getBrandId() {
		return brandId;
	}

	public void setBrandId(Integer brandId) {
		this.brandId = brandId;
	}

	public Short getExistVipCustFlag() {
		return existVipCustFlag;
	}

	public void setExistVipCustFlag(Short existVipCustFlag) {
		this.existVipCustFlag = existVipCustFlag;
	}

	public String getCampDrvIdStr() {
		return campDrvIdStr;
	}

	public void setCampDrvIdStr(String campDrvIdStr) {
		this.campDrvIdStr = campDrvIdStr;
	}

	public String getPartnerId() {
		return partnerId;
	}

	public void setPartnerId(String partnerId) {
		this.partnerId = partnerId;
	}

	public Short getIsTemplate() {
		return isTemplate;
	}

	public void setIsTemplate(Short isTemplate) {
		this.isTemplate = isTemplate;
	}

	public String getCampApproveCode() {
		return campApproveCode;
	}

	public void setCampApproveCode(String campApproveCode) {
		this.campApproveCode = campApproveCode;
	}

	public Short getIsContainFee() {
		return isContainFee;
	}

	public void setIsContainFee(Short isContainFee) {
		this.isContainFee = isContainFee;
	}

	public Float getTotalCost() {
		return totalCost;
	}

	public void setTotalCost(Float totalCost) {
		this.totalCost = totalCost;
	}

	public String getContact() {
		return contact;
	}

	public void setContact(String contact) {
		this.contact = contact;
	}

	public String getTelNumber() {
		return telNumber;
	}

	public void setTelNumber(String telNumber) {
		this.telNumber = telNumber;
	}

	public String getMsmCampsegId() {
		return msmCampsegId;
	}

	public void setMsmCampsegId(String msmCampsegId) {
		this.msmCampsegId = msmCampsegId;
	}

	public String getFirstApproveUserId() {
		return firstApproveUserId;
	}

	public void setFirstApproveUserId(String firstApproveUserId) {
		this.firstApproveUserId = firstApproveUserId;
	}
	
	

}
