package com.asiainfo.biapp.mcd.model;

import com.asiainfo.biapp.mcd.util.MpmCache;

/**
 * MtlChannelDef generated by MyEclipse - Hibernate Tools
 */

public class MtlChannelDef implements java.io.Serializable {

	// Fields

	private MtlChannelDefId id;

	private Integer channelPrio;

	private String channelId;

	private Integer channeltypeId;

	private Integer contactType;
	/** 渠道（短信）发�1�7�的具体方式 */
	private Short sendTypeId;

	private String channelCampContent;
	private String filePath;
	private String channelExtendInfo;
	private Short fmtMessFlag;
	private String testProductNo;
	

	private String channelName;

	private String feedbackinfo;
	private String oriChannelContent;
	private Short ifHaveVar; //是否具有替换符,0:无;1:有
	private String execContent;
	//陕西推荐对象描述
	private String sxRecommendDesc;
	//陕西网上营业厅url
	private String onlineServiceUrl;
	
	private String exeContentType;//营销用语类型
	private String campsegInstruct;//营销指令

	private int targetUserNums;  //目标客户群
	//短信派发时限字段，用于限定渠道短信派发的时间（单位：天）:
	private Integer sendTimeLimit;
	private int updateCycle;
	
	private int paramDays;  //频次控制间隔天数
	private int paramNum;   //频次控制发送次数
	
	private Double awardMount; //奖励金额
	private String editUrl; //采编路径
	private String handleUrl; // 办理路径
	private String sendSms ; // 短信用语
	
	private String channelAdivId;  //运营位id
	private int cepTriggerFlag;  //判断是否是实施触发
	
	private boolean isChoose;  //该渠道在修改之前是否进行过操作  比如增删改查
	
	private String messageType;   //boss运营位  引用语类型
	
	private String execTitle; // 微信标题
	private String fileName;  //微信本地文件名称
//	private String fileRemoteName;  //Ftp存放的文件名称
	 
	private String eventActiveTempletId;
	private String eventInstanceDesc;
	private String eventParamJson;
	private String functionId;
	private String functionName;
	
	public String getFunctionName() {
		return functionName;
	}

	public void setFunctionName(String functionName) {
		this.functionName = functionName;
	}

	public String getFunctionId() {
		return functionId;
	}

	public void setFunctionId(String functionId) {
		this.functionId = functionId;
	}

	public String getEventActiveTempletId() {
		return eventActiveTempletId;
	}

	public void setEventActiveTempletId(String eventActiveTempletId) {
		this.eventActiveTempletId = eventActiveTempletId;
	}

	public String getEventInstanceDesc() {
		return eventInstanceDesc;
	}

	public void setEventInstanceDesc(String eventInstanceDesc) {
		this.eventInstanceDesc = eventInstanceDesc;
	}

	public String getEventParamJson() {
		return eventParamJson;
	}

	public void setEventParamJson(String eventParamJson) {
		this.eventParamJson = eventParamJson;
	}

	public String getChannelAdivId() {
		return channelAdivId;
	}

	public void setChannelAdivId(String channelAdivId) {
		this.channelAdivId = channelAdivId;
	}

	public int getTargetUserNums() {
		return targetUserNums;
	}

	public void setTargetUserNums(int targetUserNums) {
		this.targetUserNums = targetUserNums;
	}

	public int getUpdateCycle() {
		return updateCycle;
	}

	public void setUpdateCycle(int updateCycle) {
		this.updateCycle = updateCycle;
	}

	public Integer getSendTimeLimit() {
		return sendTimeLimit;
	}

	public void setSendTimeLimit(Integer sendTimeLimit) {
		this.sendTimeLimit = sendTimeLimit;
	}

	public String getExeContentType() {
		return exeContentType;
	}

	public void setExeContentType(String exeContentType) {
		this.exeContentType = exeContentType;
	}

	public String getCampsegInstruct() {
		return campsegInstruct;
	}

	public void setCampsegInstruct(String campsegInstruct) {
		this.campsegInstruct = campsegInstruct;
	}

	public boolean isChoose() {
		return isChoose;
	}

	public void setChoose(boolean isChoose) {
		this.isChoose = isChoose;
	}

	/**
	 * 扩展字段，用于派单也面显礄1�7
	 * @return
	 */
	public String getChannelName() {
		channelName = MpmCache.getInstance().getNameByKeyFromDic("dimMtlChanneltype", this.getChanneltypeId()) + "-" + MpmCache.getInstance().getNameByKeyFromDic("allChannel", this.getChanneltypeAndId());
		return channelName;
	}

	public void setChannelName(String channelName) {
		this.channelName = channelName;
	}

	/** default constructor */
	public MtlChannelDef() {
	}

	/** full constructor */
	public MtlChannelDef(MtlChannelDefId id, Integer channelPrio, String channelId, Integer channeltypeId) {
		this.id = id;
		this.channelPrio = channelPrio;
		this.channelId = channelId;
		this.channeltypeId = channeltypeId;
	}

	// Property accessors

	public MtlChannelDefId getId() {
		return id;
	}

	public String getChannelCampContent() {
		return channelCampContent;
	}

	public void setChannelCampContent(String channelCampContent) {
		this.channelCampContent = channelCampContent;
	}

	public String getFilePath() {
		return filePath;
	}

	public void setFilePath(String filePath) {
		this.filePath = filePath;
	}

	public String getChannelExtendInfo() {
		return channelExtendInfo;
	}

	public void setChannelExtendInfo(String channelExtendInfo) {
		this.channelExtendInfo = channelExtendInfo;
	}

	public Short getFmtMessFlag() {
		return fmtMessFlag;
	}

	public void setFmtMessFlag(Short fmtMessFlag) {
		this.fmtMessFlag = fmtMessFlag;
	}

	public String getTestProductNo() {
		return testProductNo;
	}

	public void setTestProductNo(String testProductNo) {
		this.testProductNo = testProductNo;
	}

	public void setId(MtlChannelDefId id) {
		this.id = id;
	}

	public Integer getChannelPrio() {
		return channelPrio;
	}

	public void setChannelPrio(Integer channelPrio) {
		this.channelPrio = channelPrio;
	}

	public String getChannelId() {
		return channelId;
	}

	public void setChannelId(String channelId) {
		this.channelId = channelId;
	}

	public Integer getChanneltypeId() {
		return channeltypeId;
	}

	public void setChanneltypeId(Integer channeltypeId) {
		this.channeltypeId = channeltypeId;
	}

	public Integer getContactType() {
		return contactType;
	}

	public void setContactType(Integer contactType) {
		this.contactType = contactType;
	}

	public String getChanneltypeAndId() {
		return channeltypeId.toString() + "_" + channelId;
	}

	public Short getSendTypeId() {
		return sendTypeId;
	}

	public void setSendTypeId(Short sendTypeId) {
		this.sendTypeId = sendTypeId;
	}

	public String getFeedbackinfo() {
		return feedbackinfo;
	}

	public void setFeedbackinfo(String feedbackinfo) {
		this.feedbackinfo = feedbackinfo;
	}

	public String getOriChannelContent() {
		return oriChannelContent;
	}

	public void setOriChannelContent(String oriChannelContent) {
		this.oriChannelContent = oriChannelContent;
	}

	public Short getIfHaveVar() {
		return ifHaveVar;
	}

	public void setIfHaveVar(Short ifHaveVar) {
		this.ifHaveVar = ifHaveVar;
	}

	public String getExecContent() {
		return execContent;
	}

	public void setExecContent(String execContent) {
		this.execContent = execContent;
	}

	public String getSxRecommendDesc() {
		return sxRecommendDesc;
	}

	public void setSxRecommendDesc(String sxRecommendDesc) {
		this.sxRecommendDesc = sxRecommendDesc;
	}

	public String getOnlineServiceUrl() {
		return onlineServiceUrl;
	}

	public void setOnlineServiceUrl(String onlineServiceUrl) {
		this.onlineServiceUrl = onlineServiceUrl;
	}

	public int getCepTriggerFlag() {
		return cepTriggerFlag;
	}

	public void setCepTriggerFlag(int cepTriggerFlag) {
		this.cepTriggerFlag = cepTriggerFlag;
	}

	public int getParamDays() {
		return paramDays;
	}

	public void setParamDays(int paramDays) {
		this.paramDays = paramDays;
	}

	public int getParamNum() {
		return paramNum;
	}

	public void setParamNum(int paramNum) {
		this.paramNum = paramNum;
	}

	public Double getAwardMount() {
		return awardMount;
	}

	public void setAwardMount(Double awardMount) {
		this.awardMount = awardMount;
	}

	public String getEditUrl() {
		return editUrl;
	}

	public void setEditUrl(String editUrl) {
		this.editUrl = editUrl;
	}

	public String getHandleUrl() {
		return handleUrl;
	}

	public void setHandleUrl(String handleUrl) {
		this.handleUrl = handleUrl;
	}

	public String getSendSms() {
		return sendSms;
	}

	public void setSendSms(String sendSms) {
		this.sendSms = sendSms;
	}

	public String getExecTitle() {
		return execTitle;
	}

	public void setExecTitle(String execTitle) {
		this.execTitle = execTitle;
	}

	public String getFileName() {
		return fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	public String getMessageType() {
		return messageType;
	}

	public void setMessageType(String messageType) {
		this.messageType = messageType;
	}

//	public String getFileRemoteName() {
//		return fileRemoteName;
//	}
//
//	public void setFileRemoteName(String fileRemoteName) {
//		this.fileRemoteName = fileRemoteName;
//	}
	
}
