package com.asiainfo.biapp.mcd.model;

/**
 * MtlPlanExecType generated by MyEclipse Persistence Tools
 */

public class MtlPlanExecType implements java.io.Serializable {

	// Fields    

	private String planExecId;

	private String planExecName;

	private Short planExecType;

	private Short planExecPeriod;

	private String planExecColumn;

	// Constructors

	/** default constructor */
	public MtlPlanExecType() {
	}

	/** minimal constructor */
	public MtlPlanExecType(Short planExecType, String planExecColumn) {
		this.planExecType = planExecType;
		this.planExecColumn = planExecColumn;
	}

	/** full constructor */
	public MtlPlanExecType(String planExecName, Short planExecType, Short planExecPeriod, String planExecColumn) {
		this.planExecName = planExecName;
		this.planExecType = planExecType;
		this.planExecPeriod = planExecPeriod;
		this.planExecColumn = planExecColumn;
	}

	// Property accessors

	public String getPlanExecId() {
		return this.planExecId;
	}

	public void setPlanExecId(String planExecId) {
		this.planExecId = planExecId;
	}

	public String getPlanExecName() {
		return this.planExecName;
	}

	public void setPlanExecName(String planExecName) {
		this.planExecName = planExecName;
	}

	public Short getPlanExecType() {
		return this.planExecType;
	}

	public void setPlanExecType(Short planExecType) {
		this.planExecType = planExecType;
	}

	public Short getPlanExecPeriod() {
		return this.planExecPeriod;
	}

	public void setPlanExecPeriod(Short planExecPeriod) {
		this.planExecPeriod = planExecPeriod;
	}

	public String getPlanExecColumn() {
		return this.planExecColumn;
	}

	public void setPlanExecColumn(String planExecColumn) {
		this.planExecColumn = planExecColumn;
	}

}
