package com.asiainfo.biapp.mcd.common.vo.custgroup;

import com.asiainfo.biapp.mcd.common.util.MpmLocaleUtil;

/**
 * MtlCustGroup generated by MyEclipse Persistence Tools
 */

public class MtlCustGroup implements java.io.Serializable {

	// Fields

	/**
	 * 
	 */
	private static final long serialVersionUID = 5687616771425100867L;

	private String custGroupId;

	private String custGroupName;

	private String createUserId;

	private String cityId;

	private String createDate;

	private Short custGroupType;

	private Integer custGroupNum;

	private String custGroupSourceId;

	private String activeTempletId;

	private String custBaseMonth;
	private String custBaseDay;

	public String getCustBaseDay() {
		return custBaseDay;
	}

	public void setCustBaseDay(String custBaseDay) {
		this.custBaseDay = custBaseDay;
	}

	private Short custGroupAccessToken;

	private String custGroupTabName;

	private Short custGroupStatus;

	private String cityBySearch;

	private String userCityId;

	//private String targetuserFileId;

	//
	private Integer custGroupNumMore;

	private Integer custGroupNumLess;

	private Integer deptId;

	private String custGroupSourceName;
	
	private String custGroupDesc;
	
	private Short custTypeId;
	//caolifeng 用于保存查询条件中的创建人id
	private String createUserId2;
	
	private Short evaluateFlag;
	// Constructors

	public String getCreateUserId2() {
		return createUserId2;
	}

	public void setCreateUserId2(String createUserId2) {
		this.createUserId2 = createUserId2;
	}
	
	public Short getEvaluateFlag() {
		return evaluateFlag;
	}

	public void setEvaluateFlag(Short evaluateFlag) {
		this.evaluateFlag = evaluateFlag;
	}

	public Short getCustTypeId() {
		return custTypeId;
	}

	public void setCustTypeId(Short custTypeId) {
		this.custTypeId = custTypeId;
	}

	/** default constructor */
	public MtlCustGroup() {
	}

	/** minimal constructor */
	public MtlCustGroup(String custGroupName, String createUserId, String cityId, String createDate, Short custGroupType, Short custGroupAccessToken) {
		this.custGroupName = custGroupName;
		this.createUserId = createUserId;
		this.cityId = cityId;
		this.createDate = createDate;
		this.custGroupType = custGroupType;
		this.custGroupAccessToken = custGroupAccessToken;
	}

	/** full constructor */
	public MtlCustGroup(String custGroupName, String createUserId, String cityId, String createDate, Short custGroupType, Integer custGroupNum, String custGroupSourceId, String activeTempletId, String custBaseMonth, Short custGroupAccessToken) {
		this.custGroupName = custGroupName;
		this.createUserId = createUserId;
		this.cityId = cityId;
		this.createDate = createDate;
		this.custGroupType = custGroupType;
		this.custGroupNum = custGroupNum;
		this.custGroupSourceId = custGroupSourceId;
		this.activeTempletId = activeTempletId;
		this.custBaseMonth = custBaseMonth;
		this.custGroupAccessToken = custGroupAccessToken;
	}

	// Property accessors

	public String getCustGroupId() {
		return this.custGroupId;
	}

	public void setCustGroupId(String custGroupId) {
		this.custGroupId = custGroupId;
	}

	public String getCustGroupName() {
		return this.custGroupName;
	}

	public void setCustGroupName(String custGroupName) {
		this.custGroupName = custGroupName;
	}

	public String getCreateUserId() {
		return this.createUserId;
	}

	public void setCreateUserId(String createUserId) {
		this.createUserId = createUserId;
	}

	public String getCityId() {
		return this.cityId;
	}

	public void setCityId(String cityId) {
		this.cityId = cityId;
	}

	public String getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(String createDate) {
		this.createDate = createDate;
	}

	public Short getCustGroupType() {
		return this.custGroupType;
	}

	public void setCustGroupType(Short custGroupType) {
		this.custGroupType = custGroupType;
	}

	public Integer getCustGroupNum() {
		return this.custGroupNum;
	}

	public void setCustGroupNum(Integer custGroupNum) {
		this.custGroupNum = custGroupNum;
	}

	public String getCustGroupSourceId() {
		return this.custGroupSourceId;
	}

	public void setCustGroupSourceId(String custGroupSourceId) {
		this.custGroupSourceId = custGroupSourceId;
	}

	public String getActiveTempletId() {
		return this.activeTempletId;
	}

	public void setActiveTempletId(String activeTempletId) {
		this.activeTempletId = activeTempletId;
	}

	public String getCustBaseMonth() {
		return this.custBaseMonth;
	}

	public String getCustBaseMonthCN() {
		if (this.custBaseMonth != null && this.custBaseMonth.trim().length() > 1)
			return this.custBaseMonth;
		else {
			return MpmLocaleUtil.getMessage("mcd.java.w");
		}
	}

	public void setCustBaseMonthCN(String str) {

	}

	public void setCustBaseMonth(String custBaseMonth) {
		this.custBaseMonth = custBaseMonth;
	}

	public Short getCustGroupAccessToken() {
		return this.custGroupAccessToken;
	}

	public void setCustGroupAccessToken(Short custGroupAccessToken) {
		this.custGroupAccessToken = custGroupAccessToken;
	}

	public Integer getCustGroupNumLess() {
		return custGroupNumLess;
	}

	public void setCustGroupNumLess(Integer custGroupNumLess) {
		this.custGroupNumLess = custGroupNumLess;
	}

	public Integer getCustGroupNumMore() {
		return custGroupNumMore;
	}

	public void setCustGroupNumMore(Integer custGroupNumMore) {
		this.custGroupNumMore = custGroupNumMore;
	}

	public Short getCustGroupStatus() {
		return custGroupStatus;
	}

	public void setCustGroupStatus(Short custGroupStatus) {
		this.custGroupStatus = custGroupStatus;
	}

	public String getCustGroupTabName() {
		return custGroupTabName;
	}

	public void setCustGroupTabName(String custGroupTabName) {
		this.custGroupTabName = custGroupTabName;
	}

	/**
	 * @return cityBySearch
	 */
	public String getCityBySearch() {
		return cityBySearch;
	}

	/**
	 * @param cityBySearch 要设置的 cityBySearch
	 */
	public void setCityBySearch(String cityBySearch) {
		this.cityBySearch = cityBySearch;
	}

	public Integer getDeptId() {
		return deptId;
	}

	public void setDeptId(Integer deptId) {
		this.deptId = deptId;
	}

	public String getCustBaseMonthDesc() {
		String res = "";
		if (this.custBaseMonth != null && this.custBaseMonth.toLowerCase().indexOf("mtl_userday") >= 0)
			res = MpmLocaleUtil.getMessage("mcd.java.zxrb");
		else if (this.custBaseMonth != null)
			res = this.custBaseMonth;
		return res;
	}

	public void setCustBaseMonthDesc(String str) {
	}

	public String getUserCityId() {
		return userCityId;
	}

	public void setUserCityId(String userCityId) {
		this.userCityId = userCityId;
	}

	public String getCustGroupSourceName() {
		return this.custGroupSourceName;
	}

	public void setCustGroupSourceName(String custGroupSourceName) {
		this.custGroupSourceName = custGroupSourceName;
	}
	//	public String getTargetuserFileId() {
	//		return targetuserFileId;
	//	}
	//
	//	public void setTargetuserFileId(String targetuserFileId) {
	//		this.targetuserFileId = targetuserFileId;
	//	}

	public String getCustGroupDesc() {
		return custGroupDesc;
	}

	public void setCustGroupDesc(String custGroupDesc) {
		this.custGroupDesc = custGroupDesc;
	}

}
